package database

import (
	"bytes"
	"context"
	"database/sql"
	"errors"
	"fmt"
	"os"
	"slices"
	"strings"
)

const sqliteFileHeader = "SQLite format 3\x00"

const defaultSchemaTableCapacity = 16

// ValidateRestoreCandidate validates an uploaded SQLite backup file without applying it.
func (db *DB) ValidateRestoreCandidate(ctx context.Context, backupBytes []byte) error {
	if err := validateSQLiteHeader(backupBytes); err != nil {
		return err
	}

	tmpPath, err := writeTempRestoreCandidate(backupBytes)
	if err != nil {
		return err
	}
	defer func() {
		_ = os.Remove(tmpPath) //nolint:gosec // G703 false positive: tmpPath is generated by os.CreateTemp with a random suffix in the OS temp dir; no user input
	}()

	candidateDB, err := sql.Open("sqlite3", tmpPath)
	if err != nil {
		return err
	}
	defer func() {
		_ = candidateDB.Close()
	}()

	return runRestoreCandidateChecks(ctx, db.db, candidateDB)
}

func validateSQLiteHeader(backupBytes []byte) error {
	if len(backupBytes) == 0 {
		return errors.New("backup file is empty")
	}

	if len(backupBytes) < len(sqliteFileHeader) || !bytes.Equal(backupBytes[:len(sqliteFileHeader)], []byte(sqliteFileHeader)) {
		return errors.New("uploaded file is not a valid SQLite database")
	}

	return nil
}

func writeTempRestoreCandidate(backupBytes []byte) (string, error) {
	tmpFile, err := os.CreateTemp("", "madhatter-restore-*.db")
	if err != nil {
		return "", err
	}
	defer func() {
		_ = tmpFile.Close()
	}()

	tmpPath := tmpFile.Name()

	if _, err := tmpFile.Write(backupBytes); err != nil {
		return "", err
	}

	if err := tmpFile.Sync(); err != nil {
		return "", err
	}

	return tmpPath, nil
}

func runRestoreCandidateChecks(ctx context.Context, liveDB *sql.DB, candidateDB *sql.DB) error {
	if _, err := candidateDB.ExecContext(ctx, "PRAGMA foreign_keys = ON"); err != nil {
		return err
	}

	if err := validateSQLiteIntegrity(ctx, candidateDB); err != nil {
		return err
	}

	return validateMigrationCompatibility(ctx, liveDB, candidateDB)
}

func validateSQLiteIntegrity(ctx context.Context, candidateDB *sql.DB) error {
	rows, err := candidateDB.QueryContext(ctx, "PRAGMA integrity_check")
	if err != nil {
		return err
	}
	defer func() {
		_ = rows.Close()
	}()

	hasRows := false
	for rows.Next() {
		hasRows = true
		var result string
		if err := rows.Scan(&result); err != nil {
			return err
		}

		if !strings.EqualFold(result, "ok") {
			return fmt.Errorf("integrity check failed: %s", result)
		}
	}

	if err := rows.Err(); err != nil {
		return err
	}

	if !hasRows {
		return errors.New("integrity check returned no result")
	}

	return nil
}

func validateMigrationCompatibility(ctx context.Context, liveDB *sql.DB, candidateDB *sql.DB) error {
	liveVersion, liveDirty, err := GetMigrationVersion(liveDB)
	if err != nil {
		return fmt.Errorf("failed to read current migration version: %w", err)
	}

	if liveDirty {
		return errors.New("current database is in a dirty migration state")
	}

	candidateVersion, candidateDirty, err := GetMigrationVersion(candidateDB)
	if err != nil {
		return fmt.Errorf("failed to read uploaded migration version: %w", err)
	}

	if candidateDirty {
		return errors.New("uploaded backup is in a dirty migration state")
	}

	if candidateVersion > liveVersion {
		return fmt.Errorf("uploaded backup version %d is newer than current version %d", candidateVersion, liveVersion)
	}

	if candidateVersion < liveVersion {
		if err := MigrateToVersion(candidateDB, liveVersion); err != nil {
			return fmt.Errorf("failed to migrate uploaded backup from %d to %d: %w", candidateVersion, liveVersion, err)
		}

		if err := validateSchemaParity(ctx, liveDB, candidateDB); err != nil {
			return err
		}
	}

	return nil
}

func validateSchemaParity(ctx context.Context, liveDB *sql.DB, candidateDB *sql.DB) error {
	liveTables, err := listUserTables(ctx, liveDB)
	if err != nil {
		return fmt.Errorf("failed to read current schema tables: %w", err)
	}

	candidateTables, err := listUserTables(ctx, candidateDB)
	if err != nil {
		return fmt.Errorf("failed to read uploaded schema tables: %w", err)
	}

	if !slices.Equal(liveTables, candidateTables) {
		return fmt.Errorf("schema mismatch after migration: uploaded tables=%v current tables=%v", candidateTables, liveTables)
	}

	return nil
}

func listUserTables(ctx context.Context, db *sql.DB) ([]string, error) {
	rows, err := db.QueryContext(ctx, "SELECT name FROM sqlite_master WHERE type='table' AND name NOT LIKE 'sqlite_%' ORDER BY name")
	if err != nil {
		return nil, err
	}
	defer func() {
		_ = rows.Close()
	}()

	tables := make([]string, 0, defaultSchemaTableCapacity)
	for rows.Next() {
		var tableName string
		if err := rows.Scan(&tableName); err != nil {
			return nil, err
		}
		tables = append(tables, tableName)
	}

	if err := rows.Err(); err != nil {
		return nil, err
	}

	return tables, nil
}
