package database

import (
	"context"
	"testing"
	"time"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
)

// TestRecordWFHCoPresencePair_Roundtrip pins the migration 000027
// schema and the canonical-ordering normalization. Three checks:
//  1. Self-pair is a silent no-op (caller doesn't have to filter
//     identical IDs out of the on-site set).
//  2. Inverted pair (a > b) is normalized before insert so the
//     table's CHECK constraint is never tripped.
//  3. UNIQUE(working_date, a, b) means a second call is a no-op.
//
// The phase-1 migration lands the table and one writer method;
// the picker (step 9 / step 10) wires the writer into the
// presenceBuilder path. Step 9's tiebreaker reads via
// GetLatestCoPresenceWithCohort (also generated by this commit).
func TestRecordWFHCoPresencePair_Roundtrip(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	yesterday := time.Now().UTC().AddDate(0, 0, -1).Format("2006-01-02")

	// Self-pair: no-op, no error.
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, yesterday, aliceID, aliceID))

	// Inverted pair (Bob > Alice): normalized to Alice < Bob, accepted.
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, yesterday, bobID, aliceID))

	// Already-normalized pair: accepted, second call is a no-op.
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, yesterday, aliceID, bobID))
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, yesterday, aliceID, bobID))
}

// TestInsertWFHCoPresencePair_ReportsInsertVsNoop pins the
// bool return contract of the worker method used by the
// picker and backfill paths. True when the row was newly
// inserted, false when the UNIQUE(working_date, a, b)
// constraint dropped it as a duplicate (or when it's a
// self-pair). The picker uses the bool to count actual
// writes without re-reading the table.
//
// RecordWFHCoPresencePair (the error-only convenience used
// in fixture setup) delegates to this method and discards
// the bool, so any regression here breaks both surfaces.
func TestInsertWFHCoPresencePair_ReportsInsertVsNoop(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	yesterday := time.Now().UTC().AddDate(0, 0, -1).Format("2006-01-02")

	// Self-pair: never inserts, bool is false.
	inserted, err := db.InsertWFHCoPresencePair(ctx, yesterday, aliceID, aliceID)
	require.NoError(t, err)
	assert.False(t, inserted, "self-pair should be a no-op, not an insert")

	// Inverted pair (Bob > Alice) normalized at the writer.
	inserted, err = db.InsertWFHCoPresencePair(ctx, yesterday, bobID, aliceID)
	require.NoError(t, err)
	assert.True(t, inserted, "first normalised insert should report true")

	// Already-normalised pair: second call hits the UNIQUE
	// constraint and INSERT OR IGNORE skips it.
	inserted, err = db.InsertWFHCoPresencePair(ctx, yesterday, aliceID, bobID)
	require.NoError(t, err)
	assert.False(t, inserted, "duplicate insert should report false")
}

// TestPruneWFHCoPresenceOlderThan removes rows older than the
// cutoff. The settlement scheduler calls this after each tick
// (step 11) to keep the table bounded.
func TestPruneWFHCoPresenceOlderThan(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	old := time.Now().UTC().AddDate(0, 0, -10).Format("2006-01-02")
	recent := time.Now().UTC().AddDate(0, 0, -1).Format("2006-01-02")
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, old, aliceID, bobID))
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, recent, aliceID, bobID))

	// Cutoff: anything older than 5 days ago is removed.
	cutoff := time.Now().UTC().AddDate(0, 0, -5)
	require.NoError(t, db.PruneWFHCoPresenceOlderThan(ctx, cutoff))

	// Verify the old row was deleted and the recent row
	// survives. Direct row read since the package doesn't
	// have a ListCoPresence helper yet. Use julianday() so
	// the comparison is numeric regardless of the stored
	// format (the writer stores RFC3339 20-byte via
	// time.Time, but the audit-pinned boundary fix is
	// consistent — the test should mirror the production
	// lookup pattern).
	var oldCount, recentCount int
	row := db.db.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM wfh_co_presence WHERE julianday(working_date) = julianday(?)", old)
	require.NoError(t, row.Scan(&oldCount))
	row = db.db.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM wfh_co_presence WHERE julianday(working_date) = julianday(?)", recent)
	require.NoError(t, row.Scan(&recentCount))
	assert.Equal(t, 0, oldCount, "old row should be pruned")
	assert.Equal(t, 1, recentCount, "recent row should survive")
}

// TestPruneWFHCoPresenceOlderThan_TodaySurvives pins the
// boundary case at the v0.31.6 julianday() rewrite. A row
// dated today must NOT be pruned when the cutoff is today.
// The same encoding-asymmetry bug that hit wfh_assignment_swaps
// (v0.31.5) would, if the lex compare ever differed in
// precision between the stored value and the cutoff, wrongly
// delete today's row. The julianday() rewrite makes the
// comparison numeric so today's row is safe.
func TestPruneWFHCoPresenceOlderThan_TodaySurvives(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	today := time.Now().UTC().Format("2006-01-02")
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, today, aliceID, bobID))

	// Cutoff: today at midnight UTC. The pathological case.
	cutoff := time.Now().UTC().Truncate(24 * time.Hour)
	require.NoError(t, db.PruneWFHCoPresenceOlderThan(ctx, cutoff))

	var count int
	row := db.db.QueryRowContext(ctx,
		"SELECT COUNT(*) FROM wfh_co_presence WHERE julianday(working_date) = julianday(?)", today)
	require.NoError(t, row.Scan(&count))
	assert.Equal(t, 1, count,
		"a co-presence row dated today must NOT be pruned when cutoff is today — v0.31.6 julianday() rewrite")
}

// TestGetLatestCoPresenceWithCohort_LimitsToHorizon pins the
// history-clamp property: rows outside the horizon window
// are NOT considered. A row 30 days old should not lower
// the score when horizon=14.
func TestGetLatestCoPresenceWithCohort_LimitsToHorizon(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	// Insert co-presence 30 days ago (well outside horizon).
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, "old-30-days", aliceID, bobID))
	_, err = db.ExecContext(ctx,
		`UPDATE wfh_co_presence SET working_date = ? WHERE co_presence_id = ?`,
		time.Now().UTC().AddDate(0, 0, -30).Format("2006-01-02"), "old-30-days")
	require.NoError(t, err)

	// Insert co-presence 5 days ago (within horizon).
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, "recent-5-days", aliceID, bobID))
	_, err = db.ExecContext(ctx,
		`UPDATE wfh_co_presence SET working_date = ? WHERE co_presence_id = ?`,
		time.Now().UTC().AddDate(0, 0, -5).Format("2006-01-02"), "recent-5-days")
	require.NoError(t, err)

	horizonStart := time.Now().UTC().AddDate(0, 0, -14)
	now := time.Now().UTC()
	latest, err := db.GetLatestCoPresenceWithCohort(ctx, aliceID, []string{bobID}, horizonStart, now)
	require.NoError(t, err)
	assert.False(t, latest.IsZero(), "must find recent co-presence")
	// The recent row is 5 days ago; the 30-days-ago row is
	// outside the horizon and must be ignored. Assert the
	// returned date is within the horizon window — that
	// pins the property without being sensitive to clock
	// skew between the test's two time.Now() calls.
	assert.True(t, latest.After(now.AddDate(0, 0, -14)),
		"latest (%s) must be within the 14-day horizon window", latest)
	assert.True(t, latest.Before(now.AddDate(0, 0, 1)),
		"latest (%s) must be in the past", latest)
}

// TestGetLatestCoPresenceWithCohort_NoHistoryReturnsZero pins
// the NULL → zero-value contract. The picker treats zero as
// "never co-present with the cohort" and applies the
// history-clamp.
func TestGetLatestCoPresenceWithCohort_NoHistoryReturnsZero(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	horizonStart := time.Now().UTC().AddDate(0, 0, -14)
	now := time.Now().UTC()
	latest, err := db.GetLatestCoPresenceWithCohort(ctx, aliceID, []string{bobID}, horizonStart, now)
	require.NoError(t, err)
	assert.True(t, latest.IsZero(), "no history must return zero time")
}

// TestGetLatestCoPresenceWithCohort_SymmetricByNormalization
// pins that the candidate-as-B case is exercised by the
// writer's canonical-ordering normalization. RecordWFHCoPresencePair
// sorts (a, b) before insert, so a query for the candidate
// as either side of the pair finds the row regardless of
// insertion order. The CHECK constraint (member_id_a <
// member_id_b) at the storage layer enforces this — the
// raw-SQL bypass to force candidate-as-B is rejected by the
// constraint, which is itself part of the invariant.
func TestGetLatestCoPresenceWithCohort_SymmetricByNormalization(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	// Use a real YYYY-MM-DD date string so parseCoPresenceDate
	// stores the date at midnight-UTC, not the current
	// nanosecond. v0.31.6 switched the WHERE to julianday()
	// which has coarser precision than RFC3339-nanosecond;
	// a stored value at "now" against an upper bound of
	// "now" would round to the same Julian day and be
	// excluded. Production always uses a real date string
	// (the writer is called from a date-typed form field),
	// so this is the realistic shape.
	today := time.Now().UTC().Format("2006-01-02")
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, today, bobID, aliceID))

	horizonStart := time.Now().UTC().AddDate(0, 0, -14)
	now := time.Now().UTC()
	// Both queries (candidate as A and candidate as B) must
	// find the row. Asking for "alice, cohort [bob]" exercises
	// the candidate-as-B branch internally (the writer
	// normalized to (alice, bob) regardless of the inserted
	// order).
	latest, err := db.GetLatestCoPresenceWithCohort(ctx, aliceID, []string{bobID}, horizonStart, now)
	require.NoError(t, err)
	assert.False(t, latest.IsZero(),
		"co-presence must be findable after the writer normalizes the order")
}

// TestGetLatestCoPresenceWithCohort_PadsCohortToThree pins
// the cohort cap behavior at the Go wrapper level. The SQL
// pads a 5-ID cohort to the first 3 IDs via the empty-string
// sentinel approach (see GetLatestCoPresenceWithCohort). The
// SQL itself can't be tested for the cohort cap without
// bypassing the CHECK constraint, which is enforced at the
// storage layer. The Go wrapper test asserts the padding
// behavior with a single-element cohort (most common case)
// and the empty-cohort case.
func TestGetLatestCoPresenceWithCohort_PadsCohortToThree(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)

	horizonStart := time.Now().UTC().AddDate(0, 0, -14)
	now := time.Now().UTC()

	// Single-element cohort — the common case.
	latest, err := db.GetLatestCoPresenceWithCohort(ctx, aliceID, []string{"missing-member"}, horizonStart, now)
	require.NoError(t, err)
	assert.True(t, latest.IsZero(), "no history → zero time")

	// Empty cohort — the "everyone exempt" branch.
	latest, err = db.GetLatestCoPresenceWithCohort(ctx, aliceID, nil, horizonStart, now)
	require.NoError(t, err)
	assert.True(t, latest.IsZero(), "empty cohort → zero time")

	// 5-element cohort — the first 3 are used, the rest are
	// silently dropped (the empty-string padding). With no
	// co-presence rows at all, returns zero.
	latest, err = db.GetLatestCoPresenceWithCohort(ctx, aliceID,
		[]string{"x", "y", "z", "w", "v"}, horizonStart, now)
	require.NoError(t, err)
	assert.True(t, latest.IsZero(), "5-ID cohort → first 3 used, no history → zero")
}

// TestGetLatestCoPresenceWithCohort_MidnightUpperBound pins the
// defensive rewrite in v0.31.6. The picker passes time.Now().UTC()
// as the upper bound, which happens to be exactly midnight UTC
// when the picker runs at 00:00:00Z. The previous form of the
// query used the lex compare 'working_date < ?' where ? was the
// midnight-UTC RFC3339 string. The stored working_date is also
// at midnight UTC (the writer always parses a YYYY-MM-DD string
// via time.Parse("2006-01-02", ...)), so the lex compare of
// "today's row" < "today at midnight" was FALSE — today's row
// was excluded on the boundary day. Same shape as the swap
// v0.31.5 bug, latent for co-presence because the picker
// normally runs well after midnight UTC.
//
// The v0.31.6 rewrite switches to julianday() on both sides so
// the comparison is numeric. This test asserts the picker
// correctly returns yesterday's co-presence row when the upper
// bound is exactly today's midnight UTC — proving the
// half-open [start, midnightToday) window works at the
// pathological 00:00:00Z clock time.
func TestGetLatestCoPresenceWithCohort_MidnightUpperBound(t *testing.T) {
	db, cleanup := setupTestDB(t)
	defer cleanup()

	ctx := context.Background()
	aliceID, err := db.AddTeamMember(ctx, "Alice", "alice@example.com")
	require.NoError(t, err)
	bobID, err := db.AddTeamMember(ctx, "Bob", "bob@example.com")
	require.NoError(t, err)

	// Seed yesterday's co-presence (writer stores at
	// midnight-UTC of the date string). The pathological
	// case is: at the exact midnight-UTC of today, does
	// the picker find yesterday's row (it must)?
	yesterday := time.Now().UTC().AddDate(0, 0, -1).Format("2006-01-02")
	require.NoError(t, db.RecordWFHCoPresencePair(ctx, yesterday, aliceID, bobID))

	// Upper bound: exactly today at midnight UTC. The
	// pathological case the v0.31.6 rewrite guards against.
	midnightToday := time.Now().UTC().Truncate(24 * time.Hour)
	horizonStart := midnightToday.AddDate(0, 0, -14)

	latest, err := db.GetLatestCoPresenceWithCohort(ctx, aliceID, []string{bobID}, horizonStart, midnightToday)
	require.NoError(t, err)
	assert.False(t, latest.IsZero(),
		"yesterday's co-presence must be findable when upper bound is exactly today's midnight UTC — v0.31.6 julianday() rewrite")
	expected, _ := time.Parse("2006-01-02", yesterday)
	assert.True(t, latest.Equal(expected),
		"the returned date must be yesterday's midnight, not the zero time or some other date")
}
