package web

import (
	"bytes"
	"context"
	"embed"
	"errors"
	"html/template"
	"net/http"
	"net/mail"
	"os"
	"sort"
	"strings"
	"time"

	"github.com/go-chi/chi/v5"
	"github.com/inful/madhatter/internal/auth"
	"github.com/inful/madhatter/internal/calendar"
	"github.com/inful/madhatter/internal/database"
	"github.com/inful/madhatter/internal/rota"
)

//go:embed templates/*.html
var templateFS embed.FS

const (
	weekDaysCount                = 10
	weekDaysOffset               = 4
	schedulePrealloc             = 5
	defaultCalendarLookaheadDays = 90
	weekDaysInWeek               = 7
	defaultHolidayLookaheadDays  = 30
	maxStringLength              = 255
	dictKeyValuePairs            = 2
)

type Handler struct {
	db             *database.DB
	maintenance    *rota.ScheduleMaintenance
	tmpl           *template.Template
	router         *chi.Mux
	authManager    *auth.AuthManager
	authMiddleware *auth.Middleware
	holidayChecker func(time.Time) bool
	development    bool
}

type presenceDay struct {
	DateISO     string
	DateDisplay string
	IsToday     bool
	Assigned    *database.TeamMember
	Present     []database.TeamMember
	Away        []presenceLeave
}

type presenceLeave struct {
	Member database.TeamMember
}

func NewHandler(db *database.DB, authManager *auth.AuthManager, authMiddleware *auth.Middleware, development bool, holidayChecker func(time.Time) bool) (*Handler, error) {
	// Parse templates - use absolute path based on working directory
	// Try multiple possible locations for templates
	tmpl, err := parseTemplates()
	if err != nil {
		return nil, err
	}

	router := chi.NewRouter()

	h := &Handler{
		db:             db,
		maintenance:    rota.NewScheduleMaintenance(db),
		tmpl:           tmpl,
		router:         router,
		authManager:    authManager,
		authMiddleware: authMiddleware,
		holidayChecker: holidayChecker,
		development:    development,
	}

	h.registerRoutes()

	// Register development-specific routes if in development mode
	if development {
		h.registerDevelopmentRoutes()
	}

	return h, nil
}

// safeAuthMiddleware wraps middleware to handle nil auth components gracefully.
func (h *Handler) safeAuthMiddleware(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if h.authMiddleware == nil {
			// No authentication configured, proceed without auth
			next.ServeHTTP(w, r)
			return
		}
		// Use the actual middleware
		h.authMiddleware.OptionalAuth(next).ServeHTTP(w, r)
	})
}

// safeRequireAuth wraps middleware to handle nil auth components gracefully.
func (h *Handler) safeRequireAuth(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if h.authMiddleware == nil {
			// No authentication configured - show error
			http.Error(w, "Authentication required but not configured. Please set up OAuth provider environment variables.", http.StatusUnauthorized)
			return
		}
		// Use the actual middleware
		h.authMiddleware.RequireAuth(next).ServeHTTP(w, r)
	})
}

// safeRequireAdmin wraps middleware to handle nil auth components gracefully.
func (h *Handler) safeRequireAdmin(next http.Handler) http.Handler {
	return http.HandlerFunc(func(w http.ResponseWriter, r *http.Request) {
		if h.authMiddleware == nil {
			// No authentication configured - show error
			http.Error(w, "Admin access required but authentication not configured. Please set up OAuth provider environment variables.", http.StatusUnauthorized)
			return
		}
		// Use the actual middleware
		h.authMiddleware.RequireAdmin(next).ServeHTTP(w, r)
	})
}

func parseTemplates() (*template.Template, error) {
	var tmpl *template.Template

	funcMap := template.FuncMap{
		"dict": func(values ...any) map[string]any {
			if len(values)%dictKeyValuePairs != 0 {
				panic("dict requires an even number of arguments")
			}

			dict := make(map[string]any, len(values)/dictKeyValuePairs)
			for i := 0; i < len(values); i += dictKeyValuePairs {
				key, ok := values[i].(string)
				if !ok {
					panic("dict keys must be strings")
				}
				dict[key] = values[i+1]
			}

			return dict
		},
		"render": func(name string, data any) (template.HTML, error) {
			if tmpl == nil {
				return "", errors.New("templates not initialized")
			}

			var buf bytes.Buffer
			if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
				return "", err
			}
			//nolint:gosec // This HTML is generated by html/template and is already context-escaped.
			return template.HTML(buf.String()), nil
		},
		"renderAttrOptional": func(name string, data any) (template.HTMLAttr, error) {
			if tmpl == nil {
				return "", errors.New("templates not initialized")
			}

			if tmpl.Lookup(name) == nil {
				return "", nil
			}

			var buf bytes.Buffer
			if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
				return "", err
			}
			//nolint:gosec // This HTML attribute is generated by html/template and is already context-escaped.
			return template.HTMLAttr(buf.String()), nil
		},
	}

	tmpl, err := template.New("base").Funcs(funcMap).ParseFS(templateFS, "templates/*.html")
	if err != nil {
		return nil, err
	}

	return tmpl, nil
}

func (h *Handler) registerRoutes() {
	// Auth routes (no authentication required) - only if auth is configured
	if h.authManager != nil {
		// In development mode, skip registering the production login handler
		// The development handler will be registered later in registerDevelopmentRoutes()
		if !h.development {
			h.router.HandleFunc("/login", h.authManager.HandleLoginView)
		}
		h.router.HandleFunc("/auth/login/{provider}", h.authManager.HandleLogin)
		h.router.HandleFunc("/auth/callback", h.authManager.HandleCallback)
		h.router.HandleFunc("/auth/logout", h.authManager.HandleLogout)
	} else {
		// Provide a helpful page instead of a 404 when auth is disabled.
		h.router.HandleFunc("/login", h.handleLoginUnavailable)
	}

	// Public routes (no authentication required, but user info loaded if available)
	if h.authMiddleware != nil {
		// When auth is configured, hide the schedule until the user has authenticated.
		h.router.Group(func(r chi.Router) {
			r.Use(h.safeRequireAuth)
			r.HandleFunc("/", h.handleDashboard)
		})
	} else {
		h.router.Group(func(r chi.Router) {
			r.Use(h.safeAuthMiddleware)
			r.HandleFunc("/", h.handleDashboard)
		})
	}
	h.router.HandleFunc("/calendar/{token}/ics", h.handleCalendarICS)
	h.router.HandleFunc("/calendar/{token}/meetings.ics", h.handleMeetingsCalendarICS)

	// Protected routes (require authentication)
	h.router.Group(func(r chi.Router) {
		r.Use(h.safeRequireAuth)

		r.HandleFunc("/leave/report", h.handleLeaveReport)
		r.HandleFunc("/calendar", h.handleCalendar)
	})

	// Admin routes (require authentication and admin privileges)
	h.router.Group(func(r chi.Router) {
		r.Use(h.safeRequireAuth)
		r.Use(h.safeRequireAdmin)

		r.HandleFunc("/team", h.handleTeam)
		r.HandleFunc("/team/{id}/edit", h.handleTeamMemberEdit)
		r.HandleFunc("/team/{id}/delete", h.handleTeamMemberDelete)
		r.HandleFunc("/leave/manage", h.handleLeaveManagement)
		r.HandleFunc("/leave/{id}/edit", h.handleLeaveEdit)
		r.HandleFunc("/leave/{id}/delete", h.handleLeaveDelete)
		r.HandleFunc("/schedule/generate", h.handleScheduleGenerate)
	})
}

// registerDevelopmentRoutes adds development-specific routes.
func (h *Handler) registerDevelopmentRoutes() {
	if h.authManager == nil {
		return
	}

	// Check if this is a fake provider
	provider, err := h.authManager.GetProvider("fake")
	if err != nil || provider == nil {
		return
	}

	// Override the login view to show development mode message
	h.router.HandleFunc("/login", h.handleDevelopmentLogin)
}

func (h *Handler) handleDevelopmentLogin(w http.ResponseWriter, r *http.Request) {
	// Check if already logged in
	if h.isUserLoggedIn(r) {
		http.Redirect(w, r, "/", http.StatusSeeOther)
		return
	}

	// Show development mode login page
	h.renderDevelopmentLogin(w)
}

func (h *Handler) isUserLoggedIn(r *http.Request) bool {
	token, err := h.authManager.GetSessionManager().GetSessionCookie(r)
	if err != nil {
		return false
	}

	_, err = h.authManager.GetSessionManager().ValidateSession(r.Context(), token)
	return err == nil
}

func (h *Handler) renderDevelopmentLogin(w http.ResponseWriter) {
	w.Header().Set("Content-Type", "text/html")
	// Use shared HTML from auth package to eliminate duplication
	_, _ = w.Write([]byte(auth.GetDevelopmentLoginHTML()))
}

// Router returns the underlying chi router.
func (h *Handler) Router() *chi.Mux {
	return h.router
}

func (h *Handler) handleDashboard(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	data := map[string]any{
		"Today":    time.Now().Format("Monday, Jan 2, 2006"),
		"Template": "dashboard",
	}

	data["AuthEnabled"] = h.authManager != nil && h.authMiddleware != nil

	// Add user info to data
	if user, ok := auth.GetUserFromContext(ctx); ok {
		data["User"] = user
		data["IsAdmin"] = user.IsAdmin.Valid && user.IsAdmin.Int64 == 1
	}

	// Check team members - show message if none exist, but always load schedule
	members, err := h.db.GetActiveTeamMembers(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	if len(members) == 0 {
		data["NoTeamMessage"] = "No team members found. Please add team members to get started."
	}

	// Always maintain and load schedule, even if no team members
	_, err = h.maintenance.EnsureSchedule(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Load dashboard data
	h.loadDashboardData(ctx, data)

	// Render template
	if err := h.tmpl.ExecuteTemplate(w, "dashboard.html", data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (h *Handler) handleLoginUnavailable(w http.ResponseWriter, _ *http.Request) {
	w.Header().Set("Content-Type", "text/plain; charset=utf-8")
	w.WriteHeader(http.StatusServiceUnavailable)
	_, _ = w.Write([]byte("Authentication is disabled on this server.\n\nTo enable login, configure OAuth provider environment variables (see AUTH_SETUP.md), or run the server with --development for fake login during local development.\n"))
}

// loadDashboardData populates the dashboard with today's and week's assignments.
func (h *Handler) loadDashboardData(ctx context.Context, data map[string]any) {
	// Get today's assignment
	today := time.Now().Format("2006-01-02")
	assignments, err := h.db.GetAssignmentsByDate(ctx, today)
	if err == nil && len(assignments) > 0 {
		data["TodayAssignment"] = assignments[0]
	}

	// Get upcoming presence for next business days
	if presence, presenceErr := h.getUpcomingPresence(ctx); presenceErr == nil {
		data["UpcomingPresence"] = presence
	}

	// Get current and next week assignments
	weeksData, err := h.getFullWeeks(ctx)
	if err == nil {
		data["CurrentWeek"] = h.buildWeekData(weeksData, true)
		data["NextWeek"] = h.buildWeekData(weeksData, false)
	}

	// Get upcoming holidays
	if h.holidayChecker != nil {
		data["UpcomingHolidays"] = h.getUpcomingHolidays()
	}
}

// getUpcomingHolidays returns upcoming holidays for the configured lookahead days.
func (h *Handler) getUpcomingHolidays() []map[string]any {
	var holidays []map[string]any
	now := time.Now()
	endDate := now.AddDate(0, 0, defaultHolidayLookaheadDays)

	for d := now; d.Before(endDate); d = d.AddDate(0, 0, 1) {
		// Skip weekends - they are not holidays
		if d.Weekday() == time.Saturday || d.Weekday() == time.Sunday {
			continue
		}

		// Check if it's an actual holiday (not just a skipped date)
		if h.holidayChecker(d) {
			holidays = append(holidays, map[string]any{
				"Date": d.Format("2006-01-02"),
				"Name": "Holiday",
			})
		}
	}

	return holidays
}

func (h *Handler) isBusinessDay(date time.Time) bool {
	if date.Weekday() == time.Saturday || date.Weekday() == time.Sunday {
		return false
	}

	if h.holidayChecker != nil && h.holidayChecker(date) {
		return false
	}

	return true
}

func (h *Handler) getUpcomingPresence(ctx context.Context) ([]presenceDay, error) {
	return h.getUpcomingPresenceFrom(ctx, time.Now())
}

// getAssignedMember fetches the assigned member for a given date.
func (h *Handler) getAssignedMember(ctx context.Context, dateStr string, memberMap map[string]database.TeamMember) *database.TeamMember {
	assignments, err := h.db.GetAssignmentsByDate(ctx, dateStr)
	if err != nil {
		return nil
	}

	// Prioritize cover assignment - they're the one actually doing support
	for i := range assignments {
		if assignments[i].IsCover {
			if member, ok := memberMap[assignments[i].MemberID]; ok {
				return &member
			}
		}
	}

	// Fall back to original assignment if no cover
	for i := range assignments {
		if !assignments[i].IsCover {
			if member, ok := memberMap[assignments[i].MemberID]; ok {
				return &member
			}
		}
	}

	return nil
}

// buildPresenceList creates a sorted list of present members.
func buildPresenceList(memberMap map[string]database.TeamMember, onLeave map[string]struct{}) []database.TeamMember {
	present := make([]database.TeamMember, 0, len(memberMap)-len(onLeave))

	for id, member := range memberMap {
		if _, absent := onLeave[id]; absent {
			continue
		}
		present = append(present, member)
	}

	sort.Slice(present, func(i, j int) bool {
		return present[i].Name < present[j].Name
	})

	return present
}

func (h *Handler) getUpcomingPresenceFrom(ctx context.Context, start time.Time) ([]presenceDay, error) {
	members, err := h.db.GetActiveTeamMembers(ctx)
	if err != nil {
		return nil, err
	}

	memberMap := make(map[string]database.TeamMember, len(members))
	for _, member := range members {
		memberMap[member.ID] = member
	}

	current := start
	presence := make([]presenceDay, 0, weekDaysCount)

	for len(presence) < weekDaysCount {
		if !h.isBusinessDay(current) {
			current = current.AddDate(0, 0, 1)
			continue
		}

		dateStr := current.Format("2006-01-02")
		assigned := h.getAssignedMember(ctx, dateStr, memberMap)

		leaveRecords, leaveErr := h.db.GetLeaveByDate(ctx, dateStr)
		if leaveErr != nil {
			return nil, leaveErr
		}

		away := make([]presenceLeave, 0, len(leaveRecords))
		onLeave := make(map[string]struct{})
		for i := range leaveRecords {
			leave := &leaveRecords[i]
			member, ok := memberMap[leave.MemberID]
			if !ok {
				continue
			}
			onLeave[leave.MemberID] = struct{}{}
			away = append(away, presenceLeave{
				Member: member,
			})
		}

		present := buildPresenceList(memberMap, onLeave)

		sort.Slice(away, func(i, j int) bool {
			return away[i].Member.Name < away[j].Member.Name
		})

		now := time.Now()
		isToday := current.Year() == now.Year() && current.YearDay() == now.YearDay()

		presence = append(presence, presenceDay{
			DateISO:     dateStr,
			DateDisplay: current.Format("Mon, Jan 2"),
			IsToday:     isToday,
			Assigned:    assigned,
			Present:     present,
			Away:        away,
		})

		current = current.AddDate(0, 0, 1)
	}

	return presence, nil
}

// buildWeekData builds week data for dashboard display.
func (h *Handler) buildWeekData(weeksData map[string][]database.RotaAssignment, isCurrentWeek bool) []map[string]any {
	now := time.Now()
	weekStart := now.AddDate(0, 0, -int(now.Weekday())+1)
	if !isCurrentWeek {
		weekStart = weekStart.AddDate(0, 0, weekDaysInWeek)
	}
	weekEnd := weekStart.AddDate(0, 0, weekDaysOffset)

	var week []map[string]any
	for d := weekStart; d.Before(weekEnd.AddDate(0, 0, 1)); d = d.AddDate(0, 0, 1) {
		dateStr := d.Format("2006-01-02")
		isHoliday := h.holidayChecker != nil && h.holidayChecker(d)

		var assignment database.RotaAssignment
		if assignments, ok := weeksData[dateStr]; ok && len(assignments) > 0 {
			assignment = assignments[0]
		} else {
			assignment = database.RotaAssignment{
				Date:       dateStr,
				MemberName: "Unassigned",
			}
		}

		week = append(week, map[string]any{
			"Assignment": assignment,
			"IsHoliday":  isHoliday,
		})
	}
	return week
}

// getFullWeeks retrieves assignments for current and next week.
func (h *Handler) getFullWeeks(ctx context.Context) (map[string][]database.RotaAssignment, error) {
	now := time.Now()

	// Current week (Monday to Friday)
	currentWeekStart := now.AddDate(0, 0, -int(now.Weekday())+1)

	// Next week (Monday to Friday)
	nextWeekStart := currentWeekStart.AddDate(0, 0, weekDaysInWeek)
	nextWeekEnd := nextWeekStart.AddDate(0, 0, weekDaysOffset)

	// Get all assignments for both weeks
	startDate := currentWeekStart.Format("2006-01-02")
	endDate := nextWeekEnd.Format("2006-01-02")

	assignments, err := h.db.GetAssignmentsByDateRange(ctx, startDate, endDate)
	if err != nil {
		return nil, err
	}

	// Build map by date
	result := make(map[string][]database.RotaAssignment)
	for _, a := range assignments {
		result[a.Date] = append(result[a.Date], a)
	}

	return result, nil
}

func (h *Handler) handleTeam(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	data := map[string]any{
		"Template": "team",
	}

	// Add user info to data
	if user, ok := auth.GetUserFromContext(ctx); ok {
		data["User"] = user
		data["IsAdmin"] = user.IsAdmin.Valid && user.IsAdmin.Int64 == 1
	}

	if r.Method == http.MethodPost {
		if err := r.ParseForm(); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		name := r.FormValue("name")
		email := r.FormValue("email")

		_, err := h.db.AddTeamMember(ctx, name, email)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		// Handle team change - update schedule
		if err := h.maintenance.HandleTeamChange(ctx); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		http.Redirect(w, r, "/team", http.StatusSeeOther)
		return
	}

	members, err := h.db.GetActiveTeamMembers(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	data["Members"] = members

	if err := h.tmpl.ExecuteTemplate(w, "team.html", data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (h *Handler) handleLeaveReport(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	data := map[string]any{
		"Template": "leave_report",
	}

	// Add user info to data
	if user, ok := auth.GetUserFromContext(ctx); ok {
		data["User"] = user
		data["IsAdmin"] = user.IsAdmin.Valid && user.IsAdmin.Int64 == 1
	}

	if r.Method == http.MethodPost {
		if err := r.ParseForm(); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		memberID := r.FormValue("member_id")
		startDate := r.FormValue("start_date")
		endDate := r.FormValue("end_date")

		leaveID, err := h.db.CreateLeaveRecord(ctx, memberID, startDate, endDate)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		// Handle leave change using maintenance service
		err = h.maintenance.HandleLeaveChange(ctx, leaveID)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		http.Redirect(w, r, "/", http.StatusSeeOther)
		return
	}

	members, err := h.db.GetActiveTeamMembers(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	data["Members"] = members

	if err := h.tmpl.ExecuteTemplate(w, "leave_report.html", data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (h *Handler) handleScheduleGenerate(w http.ResponseWriter, r *http.Request) {
	if r.Method == http.MethodPost {
		h.handleScheduleGeneratePost(w, r)
		return
	}

	// GET request - show form
	h.handleScheduleGenerateGet(w, r)
}

func (h *Handler) handleScheduleGeneratePost(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	if err := r.ParseForm(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	// Validate team members
	if !h.validateTeamMembers(ctx, w) {
		return
	}

	// Parse and validate dates
	start, end, ok := h.parseDateRange(w, r)
	if !ok {
		return
	}

	// Generate schedule based on mode
	regenerate := r.FormValue("regenerate") == "on"
	var err error
	if regenerate {
		_, err = h.maintenance.RegenerateSchedule(ctx, start, end)
	} else {
		_, err = h.maintenance.GenerateMissingDays(ctx, start, end)
	}

	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	http.Redirect(w, r, "/", http.StatusSeeOther)
}

func (h *Handler) handleScheduleGenerateGet(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	if !h.validateTeamMembers(ctx, w) {
		return
	}

	data := map[string]any{
		"Template": "schedule_generate",
	}

	// Add user info to data
	if user, ok := auth.GetUserFromContext(ctx); ok {
		data["User"] = user
		data["IsAdmin"] = user.IsAdmin.Valid && user.IsAdmin.Int64 == 1
	}

	now := time.Now()
	data["DefaultStart"] = now.Format("2006-01-02")
	data["DefaultEnd"] = now.AddDate(0, 1, 0).Format("2006-01-02")

	if err := h.tmpl.ExecuteTemplate(w, "schedule_generate.html", data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (h *Handler) validateTeamMembers(ctx context.Context, w http.ResponseWriter) bool {
	members, err := h.db.GetActiveTeamMembers(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return false
	}
	if len(members) == 0 {
		http.Error(w, "No team members found. Please add team members first.", http.StatusBadRequest)
		return false
	}
	return true
}

func (h *Handler) parseDateRange(w http.ResponseWriter, r *http.Request) (time.Time, time.Time, bool) {
	startDate := r.FormValue("start_date")
	endDate := r.FormValue("end_date")

	start, err := time.Parse("2006-01-02", startDate)
	if err != nil {
		http.Error(w, "Invalid start date format", http.StatusBadRequest)
		return time.Time{}, time.Time{}, false
	}

	end, err := time.Parse("2006-01-02", endDate)
	if err != nil {
		http.Error(w, "Invalid end date format", http.StatusBadRequest)
		return time.Time{}, time.Time{}, false
	}

	return start, end, true
}

func (h *Handler) handleCalendar(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	data := map[string]any{
		"Template": "calendar",
	}

	// Add user info to data
	if user, ok := auth.GetUserFromContext(ctx); ok {
		data["User"] = user
		data["IsAdmin"] = user.IsAdmin.Valid && user.IsAdmin.Int64 == 1
	}

	if r.Method == http.MethodPost {
		if err := r.ParseForm(); err != nil {
			http.Error(w, err.Error(), http.StatusBadRequest)
			return
		}
		memberID := r.FormValue("member_id")

		token, err := h.db.CreateCalendarSubscription(ctx, memberID)
		if err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
			return
		}

		baseURL := "http://" + r.Host
		data["Token"] = token
		data["CalendarURL"] = baseURL + "/calendar/" + token + "/ics"
		data["MeetingsCalendarURL"] = baseURL + "/calendar/" + token + "/meetings.ics"
		data["ShowResult"] = true

		if err := h.tmpl.ExecuteTemplate(w, "calendar.html", data); err != nil {
			http.Error(w, err.Error(), http.StatusInternalServerError)
		}
		return
	}

	members, err := h.db.GetActiveTeamMembers(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	data["Members"] = members

	if err := h.tmpl.ExecuteTemplate(w, "calendar.html", data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (h *Handler) handleCalendarICS(w http.ResponseWriter, r *http.Request) {
	// Get token from URL
	token := chi.URLParam(r, "token")
	if token == "" {
		http.Error(w, "Token required", http.StatusBadRequest)
		return
	}

	// Generate ICS content using new calendar library
	icsContent, err := calendar.GenerateICalForToken(r.Context(), h.db, token, defaultCalendarLookaheadDays)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}

	// Set headers for calendar download
	w.Header().Set("Content-Type", "text/calendar")
	w.Header().Set("Content-Disposition", "attachment; filename=\"support-rota.ics\"")
	w.Header().Set("Cache-Control", "no-cache")

	// Write ICS content
	_, _ = w.Write([]byte(icsContent))
}

func (h *Handler) handleMeetingsCalendarICS(w http.ResponseWriter, r *http.Request) {
	// Get token from URL
	token := chi.URLParam(r, "token")
	if token == "" {
		http.Error(w, "Token required", http.StatusBadRequest)
		return
	}

	teamsURL := os.Getenv("MEETINGS_TEAMS_URL")
	tz := os.Getenv("MEETINGS_TIMEZONE")

	icsContent, err := calendar.GenerateMeetingsICalForToken(
		r.Context(),
		h.db,
		token,
		defaultCalendarLookaheadDays,
		calendar.MeetingsOptions{Timezone: tz, TeamsURL: teamsURL},
		h.isBusinessDay,
	)
	if err != nil {
		http.Error(w, err.Error(), http.StatusNotFound)
		return
	}

	// Set headers for calendar download
	w.Header().Set("Content-Type", "text/calendar")
	w.Header().Set("Content-Disposition", "attachment; filename=\"support-meetings.ics\"")
	w.Header().Set("Cache-Control", "no-cache")

	_, _ = w.Write([]byte(icsContent))
}

// validateTeamMemberInput validates name and email inputs.
func validateTeamMemberInput(name, email string) error {
	if name == "" {
		return errors.New("name cannot be empty")
	}
	if email == "" {
		return errors.New("email cannot be empty")
	}
	if len(name) > maxStringLength {
		return errors.New("name is too long (max 255 characters)")
	}
	if len(email) > maxStringLength {
		return errors.New("email is too long (max 255 characters)")
	}
	// Validate email format
	if _, err := mail.ParseAddress(email); err != nil {
		return errors.New("invalid email format")
	}
	return nil
}

// validateLeaveDates validates and parses leave dates.
func validateLeaveDates(startDate, endDate string) (time.Time, time.Time, error) {
	const dateLayout = "2006-01-02"
	startTime, err := time.Parse(dateLayout, startDate)
	if err != nil {
		return time.Time{}, time.Time{}, errors.New("invalid start_date format, expected YYYY-MM-DD")
	}

	endTime, err := time.Parse(dateLayout, endDate)
	if err != nil {
		return time.Time{}, time.Time{}, errors.New("invalid end_date format, expected YYYY-MM-DD")
	}

	if endTime.Before(startTime) {
		return time.Time{}, time.Time{}, errors.New("end_date must be on or after start_date")
	}

	return startTime, endTime, nil
}

func (h *Handler) handleTeamMemberEdit(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	memberID := chi.URLParam(r, "id")

	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	if err := r.ParseForm(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	name := strings.TrimSpace(r.FormValue("name"))
	email := strings.TrimSpace(r.FormValue("email"))

	// Validate input at handler level
	if err := validateTeamMemberInput(name, email); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if err := h.db.UpdateTeamMember(ctx, memberID, name, email); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	http.Redirect(w, r, "/team", http.StatusSeeOther)
}

func (h *Handler) handleTeamMemberDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	memberID := chi.URLParam(r, "id")

	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	if err := h.db.DeleteTeamMember(ctx, memberID); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Handle team change - update schedule
	if err := h.maintenance.HandleTeamChange(ctx); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	http.Redirect(w, r, "/team", http.StatusSeeOther)
}

func (h *Handler) handleLeaveManagement(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	data := map[string]any{
		"Template": "leave_management",
	}

	// Add user info to data
	if user, ok := auth.GetUserFromContext(ctx); ok {
		data["User"] = user
		data["IsAdmin"] = user.IsAdmin.Valid && user.IsAdmin.Int64 == 1
	}

	// Get all leave records
	leaves, err := h.db.GetLeaveRecords(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Get all team members to enrich leave data
	members, err := h.db.GetActiveTeamMembers(ctx)
	if err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Create member map for quick lookup
	memberMap := make(map[string]database.TeamMember)
	for _, m := range members {
		memberMap[m.ID] = m
	}

	// Enrich leaves with member details
	type enrichedLeave struct {
		Leave      database.LeaveRecord
		MemberName string
	}

	enrichedLeaves := make([]enrichedLeave, 0, len(leaves))
	for i := range leaves {
		el := enrichedLeave{
			Leave:      leaves[i],
			MemberName: "Unknown",
		}
		if member, ok := memberMap[leaves[i].MemberID]; ok {
			el.MemberName = member.Name
		}
		enrichedLeaves = append(enrichedLeaves, el)
	}

	data["Leaves"] = enrichedLeaves
	data["Members"] = members

	if err := h.tmpl.ExecuteTemplate(w, "leave_management.html", data); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
	}
}

func (h *Handler) handleLeaveEdit(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	leaveID := chi.URLParam(r, "id")

	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	if err := r.ParseForm(); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	memberID := strings.TrimSpace(r.FormValue("member_id"))
	startDate := strings.TrimSpace(r.FormValue("start_date"))
	endDate := strings.TrimSpace(r.FormValue("end_date"))
	status := strings.TrimSpace(r.FormValue("status"))

	// Validate input at handler level
	if memberID == "" {
		http.Error(w, "member_id cannot be empty", http.StatusBadRequest)
		return
	}
	if startDate == "" {
		http.Error(w, "start_date cannot be empty", http.StatusBadRequest)
		return
	}
	if endDate == "" {
		http.Error(w, "end_date cannot be empty", http.StatusBadRequest)
		return
	}
	if status == "" {
		http.Error(w, "status cannot be empty", http.StatusBadRequest)
		return
	}

	// Validate date format and ordering
	if _, _, err := validateLeaveDates(startDate, endDate); err != nil {
		http.Error(w, err.Error(), http.StatusBadRequest)
		return
	}

	if err := h.db.UpdateLeaveRecord(ctx, leaveID, memberID, startDate, endDate, status); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Handle leave change using maintenance service
	if err := h.maintenance.HandleLeaveChange(ctx, leaveID); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	http.Redirect(w, r, "/leave/manage", http.StatusSeeOther)
}

func (h *Handler) handleLeaveDelete(w http.ResponseWriter, r *http.Request) {
	ctx := r.Context()
	leaveID := chi.URLParam(r, "id")

	if r.Method != http.MethodPost {
		http.Error(w, "Method not allowed", http.StatusMethodNotAllowed)
		return
	}

	if err := h.db.DeleteLeaveRecord(ctx, leaveID); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	// Reconcile covers - will remove any stale covers automatically
	if err := h.maintenance.HandleTeamChange(ctx); err != nil {
		http.Error(w, err.Error(), http.StatusInternalServerError)
		return
	}

	http.Redirect(w, r, "/leave/manage", http.StatusSeeOther)
}
