package web

import (
	"bytes"
	"embed"
	"errors"
	"html/template"
)

//go:embed templates/*.html
var templateFS embed.FS

func parseTemplates() (*template.Template, error) {
	var tmpl *template.Template

	funcMap := template.FuncMap{
		"dict": func(values ...any) map[string]any {
			if len(values)%dictKeyValuePairs != 0 {
				panic("dict requires an even number of arguments")
			}

			dict := make(map[string]any, len(values)/dictKeyValuePairs)
			for i := 0; i < len(values); i += dictKeyValuePairs {
				key, ok := values[i].(string)
				if !ok {
					panic("dict keys must be strings")
				}
				dict[key] = values[i+1]
			}

			return dict
		},
		"render": func(name string, data any) (template.HTML, error) {
			if tmpl == nil {
				return "", errors.New("templates not initialized")
			}

			var buf bytes.Buffer
			if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
				return "", err
			}
			//nolint:gosec // This HTML is generated by html/template and is already context-escaped.
			return template.HTML(buf.String()), nil
		},
		"renderAttrOptional": func(name string, data any) (template.HTMLAttr, error) {
			if tmpl == nil {
				return "", errors.New("templates not initialized")
			}

			if tmpl.Lookup(name) == nil {
				return "", nil
			}

			var buf bytes.Buffer
			if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
				return "", err
			}
			//nolint:gosec // This HTML attribute is generated by html/template and is already context-escaped.
			return template.HTMLAttr(buf.String()), nil
		},
	}

	tmpl, err := template.New("base").Funcs(funcMap).ParseFS(templateFS, "templates/*.html")
	if err != nil {
		return nil, err
	}

	return tmpl, nil
}
