package web

import (
	"bytes"
	"embed"
	"errors"
	"html/template"
	"time"

	"github.com/inful/madhatter/internal/version"
)

//go:embed templates/*.html
var templateFS embed.FS

func parseTemplates() (*template.Template, error) {
	var tmpl *template.Template

	funcMap := template.FuncMap{
		// version returns the build identity of the running
		// binary as set via ldflags at link time. Falls back
		// to "dev" when unset so test fixtures and dev builds
		// render without crashing. Surfaced in the footer of
		// every page so users can see exactly which build they
		// are looking at when filing a bug.
		"version": version.Current,
		// currentDay returns today's date as a YYYY-MM-DD string.
		// Used by the base template's
		// `<meta name="current-day" content="...">` tag, which the
		// day-rollover.js wrapper reads on the client to detect
		// "stale tab open past midnight". Pages that populate
		// data["Today"] with a server-side date use that value
		// directly (so the meta tag is consistent with the rest
		// of the dashboard's date arithmetic); pages that don't
		// fall back to the client's clock via this helper so the
		// meta tag is never empty.
		"currentDay": currentDayForTemplate,
		// currentDayFromData returns data["Today"] if present,
		// else currentDayForTemplate(). Templates call this so
		// the dashboard's `<meta name="current-day" content="...">`
		// matches the server-rendered schedule date when
		// available, falling back to the client clock otherwise.
		"currentDayFromData": currentDayFromDataForTemplate,
		// csrfToken is the template helper that injects the
		// current request's CSRF cookie value as a hidden
		// form field. Form templates use it as
		// `<input type="hidden" name="csrf_token" value="{{ csrfToken }}">`
		// to participate in the double-submit CSRF pattern
		// enforced by csrfMiddleware. Reads the cookie from
		// csrfCurrentRequest (set by the middleware just
		// before the handler runs). Returns the empty
		// string outside a request scope (tests, background
		// tasks) so a form rendered without a valid cookie
		// fails the CSRF POST check rather than passing it
		// with a default value.
		"csrfToken": csrfToken,
		"dict": func(values ...any) map[string]any {
			if len(values)%dictKeyValuePairs != 0 {
				panic("dict requires an even number of arguments")
			}

			dict := make(map[string]any, len(values)/dictKeyValuePairs)
			for i := 0; i < len(values); i += dictKeyValuePairs {
				key, ok := values[i].(string)
				if !ok {
					panic("dict keys must be strings")
				}
				dict[key] = values[i+1]
			}

			return dict
		},
		"render": func(name string, data any) (template.HTML, error) {
			if tmpl == nil {
				return "", errors.New("templates not initialized")
			}

			var buf bytes.Buffer
			if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
				return "", err
			}
			//nolint:gosec // This HTML is generated by html/template and is already context-escaped.
			return template.HTML(buf.String()), nil
		},
		"renderAttrOptional": func(name string, data any) (template.HTMLAttr, error) {
			if tmpl == nil {
				return "", errors.New("templates not initialized")
			}

			if tmpl.Lookup(name) == nil {
				return "", nil
			}

			var buf bytes.Buffer
			if err := tmpl.ExecuteTemplate(&buf, name, data); err != nil {
				return "", err
			}
			//nolint:gosec // This HTML attribute is generated by html/template and is already context-escaped.
			return template.HTMLAttr(buf.String()), nil
		},
	}

	tmpl, err := template.New("base").Funcs(funcMap).ParseFS(templateFS, "templates/*.html")
	if err != nil {
		return nil, err
	}

	return tmpl, nil
}

// currentDayForTemplate returns today's date as a YYYY-MM-DD
// string in the server's local time zone. Used by the
// current-day meta tag on pages that don't have a server-
// computed "today" (e.g. login screen, calendar subscriptions).
// Pages that do have a server-computed today (the dashboard)
// use currentDayFromDataForTemplate so the meta tag matches
// the rest of the page's date arithmetic.
func currentDayForTemplate() string {
	return time.Now().Format("2006-01-02")
}

// currentDayFromDataForTemplate returns data["Today"] when
// present (dashboard path), else falls back to the server's
// current date (other paths). Templates use this so the
// meta tag matches whichever "today" the rest of the page
// was rendered against.
func currentDayFromDataForTemplate(data map[string]any) string {
	if v, ok := data["Today"].(string); ok && v != "" {
		return v
	}
	return currentDayForTemplate()
}
