version: 2

project_name: madhatter

before:
  hooks:
    - go mod download
    - go mod tidy

builds:
  - id: madhatter
    main: ./main.go
    binary: madhatter
    env:
      - CGO_ENABLED=0
    goos:
      - linux
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X github.com/inful/madhatter/internal/version.Version={{.Version}}
      - -X github.com/inful/madhatter/internal/version.Commit={{.Commit}}
      - -X github.com/inful/madhatter/internal/version.Date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"

dockers_v2:
    - images:
        - "ghcr.io/inful/{{ .ProjectName }}"
      tags:
        - "{{ .Version }}"
        - "latest"
      labels:
        "org.opencontainers.image.title": "{{ .ProjectName }}"
        "org.opencontainers.image.description": "Madhatter support rota scheduling system"
        "org.opencontainers.image.url": "https://github.com/inful/{{ .ProjectName }}"
        "org.opencontainers.image.source": "https://github.com/inful/{{ .ProjectName }}"
        "org.opencontainers.image.version": "{{ .Version }}"
        "org.opencontainers.image.revision": "{{ .FullCommit }}"
        "org.opencontainers.image.created": "{{ .Date }}"
release:
  github:
    owner: inful
    name: madhatter
  name_template: "Version {{.Version}}"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
      - "^ci:"
