-- Add the wfh_co_presence table that records which members were
-- on-site together on a given working day. The seat-cap picker
-- (step 6 / step 9 of plans/assigned-wfh-plan.md) uses this
-- history as the co-presence tiebreaker: a candidate who hasn't
-- been on-site with the cohort recently gets a low priority
-- (the picker keeps them on-site so they meet the cohort).
--
-- Rows are unordered pairs (canonical ordering member_id_a <
-- member_id_b) — halves the row count and removes the
-- symmetric-pair problem. UNIQUE(working_date, a, b) enforces
-- the canonical ordering at the storage layer; if the writer
-- accidentally tries to insert (a=2, b=1) the CHECK rejects it.
--
-- The three indexes support three access patterns:
--   1. (working_date) — backfill retention prune.
--   2. (member_id_a, working_date) — "for candidate X, when did
--      I last co-present with anyone in cohort Y?" The picker
--      query in step 9 uses both sides via OR.
--   3. (member_id_b, working_date) — symmetric.
--
-- The co_presence_id PK is a UUID generated by the writer. We
-- don't store member_id_a/member_id_b as a composite natural
-- key because the FKs to team_members are declared per column,
-- and a single surrogate PK keeps sqlc generated code simple.
CREATE TABLE IF NOT EXISTS wfh_co_presence (
    co_presence_id TEXT PRIMARY KEY,
    working_date DATE NOT NULL,
    member_id_a TEXT NOT NULL,
    member_id_b TEXT NOT NULL,
    recorded_at DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (member_id_a) REFERENCES team_members(id) ON DELETE CASCADE,
    FOREIGN KEY (member_id_b) REFERENCES team_members(id) ON DELETE CASCADE,
    UNIQUE(working_date, member_id_a, member_id_b),
    CHECK (member_id_a < member_id_b)
);

CREATE INDEX IF NOT EXISTS idx_wfh_co_presence_date     ON wfh_co_presence(working_date);
CREATE INDEX IF NOT EXISTS idx_wfh_co_presence_member_a ON wfh_co_presence(member_id_a, working_date);
CREATE INDEX IF NOT EXISTS idx_wfh_co_presence_member_b ON wfh_co_presence(member_id_b, working_date);
