// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cleanupExpiredTokens = `-- name: CleanupExpiredTokens :execresult
DELETE FROM api_tokens
WHERE expires_at < CURRENT_TIMESTAMP AND expires_at IS NOT NULL
`

func (q *Queries) CleanupExpiredTokens(ctx context.Context) (sql.Result, error) {
	return q.db.ExecContext(ctx, cleanupExpiredTokens)
}

const createAPIToken = `-- name: CreateAPIToken :execresult
INSERT INTO api_tokens (
    id, user_id, name, token_hash, is_active, expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?
)
`

type CreateAPITokenParams struct {
	ID        string        `json:"id"`
	UserID    string        `json:"user_id"`
	Name      string        `json:"name"`
	TokenHash string        `json:"token_hash"`
	IsActive  sql.NullInt64 `json:"is_active"`
	ExpiresAt sql.NullTime  `json:"expires_at"`
}

func (q *Queries) CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createAPIToken,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.TokenHash,
		arg.IsActive,
		arg.ExpiresAt,
	)
}

const deactivateAPIToken = `-- name: DeactivateAPIToken :execresult
UPDATE api_tokens
SET is_active = 0
WHERE id = ?
`

func (q *Queries) DeactivateAPIToken(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deactivateAPIToken, id)
}

const deleteAPIToken = `-- name: DeleteAPIToken :execresult
DELETE FROM api_tokens
WHERE id = ?
`

func (q *Queries) DeleteAPIToken(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteAPIToken, id)
}

const getAPITokenByHash = `-- name: GetAPITokenByHash :one
SELECT 
    id, user_id, name, token_hash, is_active, created_at, expires_at, last_used_at
FROM api_tokens
WHERE token_hash = ? AND is_active = 1
    AND (expires_at IS NULL OR expires_at > CURRENT_TIMESTAMP)
`

func (q *Queries) GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByHash, tokenHash)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPITokenByID = `-- name: GetAPITokenByID :one
SELECT 
    id, user_id, name, token_hash, is_active, created_at, expires_at, last_used_at
FROM api_tokens
WHERE id = ?
`

func (q *Queries) GetAPITokenByID(ctx context.Context, id string) (ApiToken, error) {
	row := q.db.QueryRowContext(ctx, getAPITokenByID, id)
	var i ApiToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.ExpiresAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getAPITokensByUser = `-- name: GetAPITokensByUser :many
SELECT 
    id, user_id, name, token_hash, is_active, created_at, expires_at, last_used_at
FROM api_tokens
WHERE user_id = ?
ORDER BY created_at DESC
`

func (q *Queries) GetAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error) {
	rows, err := q.db.QueryContext(ctx, getAPITokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiToken{}
	for rows.Next() {
		var i ApiToken
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.TokenHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.ExpiresAt,
			&i.LastUsedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPITokenLastUsed = `-- name: UpdateAPITokenLastUsed :execresult
UPDATE api_tokens
SET last_used_at = CURRENT_TIMESTAMP
WHERE id = ?
`

func (q *Queries) UpdateAPITokenLastUsed(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateAPITokenLastUsed, id)
}
