// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: calendar_subscriptions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCalendarSubscription = `-- name: CreateCalendarSubscription :execresult
INSERT INTO calendar_subscriptions (id, member_id, token)
VALUES (?, ?, ?)
`

type CreateCalendarSubscriptionParams struct {
	ID       string `json:"id"`
	MemberID string `json:"member_id"`
	Token    string `json:"token"`
}

func (q *Queries) CreateCalendarSubscription(ctx context.Context, arg CreateCalendarSubscriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCalendarSubscription, arg.ID, arg.MemberID, arg.Token)
}

const deleteCalendarSubscription = `-- name: DeleteCalendarSubscription :exec
DELETE FROM calendar_subscriptions
WHERE token = ?
`

func (q *Queries) DeleteCalendarSubscription(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarSubscription, token)
	return err
}

const deleteMemberSubscriptions = `-- name: DeleteMemberSubscriptions :exec
DELETE FROM calendar_subscriptions
WHERE member_id = ?
`

func (q *Queries) DeleteMemberSubscriptions(ctx context.Context, memberID string) error {
	_, err := q.db.ExecContext(ctx, deleteMemberSubscriptions, memberID)
	return err
}

const getSubscriptionByToken = `-- name: GetSubscriptionByToken :one
SELECT id, member_id, token, created_at
FROM calendar_subscriptions
WHERE token = ?
`

func (q *Queries) GetSubscriptionByToken(ctx context.Context, token string) (CalendarSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByToken, token)
	var i CalendarSubscription
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Token,
		&i.CreatedAt,
	)
	return i, err
}

const getSubscriptionsByMemberID = `-- name: GetSubscriptionsByMemberID :many
SELECT id, member_id, token, created_at
FROM calendar_subscriptions
WHERE member_id = ?
`

func (q *Queries) GetSubscriptionsByMemberID(ctx context.Context, memberID string) ([]CalendarSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarSubscription{}
	for rows.Next() {
		var i CalendarSubscription
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Token,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
