// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: calendar_subscriptions.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createCalendarSubscription = `-- name: CreateCalendarSubscription :execresult
INSERT INTO calendar_subscriptions (id, member_id, token)
VALUES (?, ?, ?)
`

type CreateCalendarSubscriptionParams struct {
	ID       string `json:"id"`
	MemberID string `json:"member_id"`
	Token    string `json:"token"`
}

func (q *Queries) CreateCalendarSubscription(ctx context.Context, arg CreateCalendarSubscriptionParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createCalendarSubscription, arg.ID, arg.MemberID, arg.Token)
}

const deleteCalendarSubscription = `-- name: DeleteCalendarSubscription :exec
DELETE FROM calendar_subscriptions
WHERE token = ?
`

func (q *Queries) DeleteCalendarSubscription(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, deleteCalendarSubscription, token)
	return err
}

const deleteMemberSubscriptions = `-- name: DeleteMemberSubscriptions :exec
DELETE FROM calendar_subscriptions
WHERE member_id = ?
`

func (q *Queries) DeleteMemberSubscriptions(ctx context.Context, memberID string) error {
	_, err := q.db.ExecContext(ctx, deleteMemberSubscriptions, memberID)
	return err
}

const deleteStaleSubscriptions = `-- name: DeleteStaleSubscriptions :execresult
DELETE FROM calendar_subscriptions
WHERE last_used_at < ?
   OR (last_used_at IS NULL AND created_at < ?)
`

type DeleteStaleSubscriptionsParams struct {
	LastUsedAt sql.NullTime `json:"last_used_at"`
	CreatedAt  sql.NullTime `json:"created_at"`
}

func (q *Queries) DeleteStaleSubscriptions(ctx context.Context, arg DeleteStaleSubscriptionsParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, deleteStaleSubscriptions, arg.LastUsedAt, arg.CreatedAt)
}

const getAllSubscriptions = `-- name: GetAllSubscriptions :many
SELECT id, member_id, token, created_at, last_used_at, last_used_rota_at, last_used_meetings_at
FROM calendar_subscriptions
ORDER BY last_used_at ASC NULLS FIRST
`

func (q *Queries) GetAllSubscriptions(ctx context.Context) ([]CalendarSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getAllSubscriptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarSubscription{}
	for rows.Next() {
		var i CalendarSubscription
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Token,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.LastUsedRotaAt,
			&i.LastUsedMeetingsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSubscriptionByToken = `-- name: GetSubscriptionByToken :one
SELECT id, member_id, token, created_at, last_used_at, last_used_rota_at, last_used_meetings_at
FROM calendar_subscriptions
WHERE token = ?
`

func (q *Queries) GetSubscriptionByToken(ctx context.Context, token string) (CalendarSubscription, error) {
	row := q.db.QueryRowContext(ctx, getSubscriptionByToken, token)
	var i CalendarSubscription
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Token,
		&i.CreatedAt,
		&i.LastUsedAt,
		&i.LastUsedRotaAt,
		&i.LastUsedMeetingsAt,
	)
	return i, err
}

const getSubscriptionsByMemberID = `-- name: GetSubscriptionsByMemberID :many
SELECT id, member_id, token, created_at, last_used_at, last_used_rota_at, last_used_meetings_at
FROM calendar_subscriptions
WHERE member_id = ?
`

func (q *Queries) GetSubscriptionsByMemberID(ctx context.Context, memberID string) ([]CalendarSubscription, error) {
	rows, err := q.db.QueryContext(ctx, getSubscriptionsByMemberID, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CalendarSubscription{}
	for rows.Next() {
		var i CalendarSubscription
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Token,
			&i.CreatedAt,
			&i.LastUsedAt,
			&i.LastUsedRotaAt,
			&i.LastUsedMeetingsAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const touchMeetingsSubscription = `-- name: TouchMeetingsSubscription :exec
UPDATE calendar_subscriptions
SET last_used_at = CURRENT_TIMESTAMP,
    last_used_meetings_at = CURRENT_TIMESTAMP
WHERE token = ?
`

func (q *Queries) TouchMeetingsSubscription(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, touchMeetingsSubscription, token)
	return err
}

const touchRotaSubscription = `-- name: TouchRotaSubscription :exec
UPDATE calendar_subscriptions
SET last_used_at = CURRENT_TIMESTAMP,
    last_used_rota_at = CURRENT_TIMESTAMP
WHERE token = ?
`

func (q *Queries) TouchRotaSubscription(ctx context.Context, token string) error {
	_, err := q.db.ExecContext(ctx, touchRotaSubscription, token)
	return err
}
