// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cover_rotation_state.sql

package sqlc

import (
	"context"
	"time"
)

const getCoverRotationState = `-- name: GetCoverRotationState :one
SELECT last_date, last_index
FROM cover_rotation_state
WHERE id = 1
`

type GetCoverRotationStateRow struct {
	LastDate  time.Time `json:"last_date"`
	LastIndex int64     `json:"last_index"`
}

// Returns the single row of the cover_rotation_state table, or
// sql.ErrNoRows if no state has been written yet (a fresh database
// has no row until the first cover is computed).
func (q *Queries) GetCoverRotationState(ctx context.Context) (GetCoverRotationStateRow, error) {
	row := q.db.QueryRowContext(ctx, getCoverRotationState)
	var i GetCoverRotationStateRow
	err := row.Scan(&i.LastDate, &i.LastIndex)
	return i, err
}

const upsertCoverRotationState = `-- name: UpsertCoverRotationState :exec
INSERT INTO cover_rotation_state (id, last_date, last_index)
VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    last_date = excluded.last_date,
    last_index = excluded.last_index
`

type UpsertCoverRotationStateParams struct {
	LastDate  time.Time `json:"last_date"`
	LastIndex int64     `json:"last_index"`
}

// Inserts the cover rotation state row if it doesn't exist, otherwise
// updates it in place. The table is constrained to a single row by
// the CHECK (id = 1) clause, so this is the only way to write it.
func (q *Queries) UpsertCoverRotationState(ctx context.Context, arg UpsertCoverRotationStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertCoverRotationState, arg.LastDate, arg.LastIndex)
	return err
}
