// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: cover_rotation_state.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const ensureReassignmentAnchorRow = `-- name: EnsureReassignmentAnchorRow :exec
INSERT OR IGNORE INTO cover_rotation_state (id) VALUES (1)
`

// INSERT-OR-IGNORE the single row of cover_rotation_state. Used by
// the reassign path so its subsequent UPDATE does not fail on a
// fresh database where the row does not exist yet. Only the id is
// inserted; the ad-hoc columns stay NULL (or whatever a prior
// ad-hoc HandleLeaveChange left them as) and the reassign columns
// are populated by the subsequent UPDATE.
func (q *Queries) EnsureReassignmentAnchorRow(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, ensureReassignmentAnchorRow)
	return err
}

const getCoverRotationState = `-- name: GetCoverRotationState :one
SELECT last_date, last_index
FROM cover_rotation_state
WHERE id = 1
`

type GetCoverRotationStateRow struct {
	LastDate  time.Time `json:"last_date"`
	LastIndex int64     `json:"last_index"`
}

// Returns the single row of the cover_rotation_state table, or
// sql.ErrNoRows if no state has been written yet (a fresh database
// has no row until the first cover is computed).
func (q *Queries) GetCoverRotationState(ctx context.Context) (GetCoverRotationStateRow, error) {
	row := q.db.QueryRowContext(ctx, getCoverRotationState)
	var i GetCoverRotationStateRow
	err := row.Scan(&i.LastDate, &i.LastIndex)
	return i, err
}

const getReassignmentAnchor = `-- name: GetReassignmentAnchor :one
SELECT last_reassign_date, last_reassign_index
FROM cover_rotation_state
WHERE id = 1
`

type GetReassignmentAnchorRow struct {
	LastReassignDate  sql.NullTime  `json:"last_reassign_date"`
	LastReassignIndex sql.NullInt64 `json:"last_reassign_index"`
}

// Reads the ReassignCovers-only anchor. Returns sql.ErrNoRows if the
// row has never been written, which signals a fresh database.
func (q *Queries) GetReassignmentAnchor(ctx context.Context) (GetReassignmentAnchorRow, error) {
	row := q.db.QueryRowContext(ctx, getReassignmentAnchor)
	var i GetReassignmentAnchorRow
	err := row.Scan(&i.LastReassignDate, &i.LastReassignIndex)
	return i, err
}

const updateReassignmentAnchor = `-- name: UpdateReassignmentAnchor :exec
UPDATE cover_rotation_state
SET last_reassign_date = ?, last_reassign_index = ?
WHERE id = 1
`

type UpdateReassignmentAnchorParams struct {
	LastReassignDate  sql.NullTime  `json:"last_reassign_date"`
	LastReassignIndex sql.NullInt64 `json:"last_reassign_index"`
}

// Updates the reassign anchor columns only. Does not touch the
// ad-hoc last_date / last_index columns, so a concurrent ad-hoc
// HandleLeaveChange is safe. The reassign path never reads or
// writes the ad-hoc state.
func (q *Queries) UpdateReassignmentAnchor(ctx context.Context, arg UpdateReassignmentAnchorParams) error {
	_, err := q.db.ExecContext(ctx, updateReassignmentAnchor, arg.LastReassignDate, arg.LastReassignIndex)
	return err
}

const upsertCoverRotationState = `-- name: UpsertCoverRotationState :exec
INSERT INTO cover_rotation_state (id, last_date, last_index)
VALUES (1, ?, ?)
ON CONFLICT (id) DO UPDATE SET
    last_date = excluded.last_date,
    last_index = excluded.last_index
`

type UpsertCoverRotationStateParams struct {
	LastDate  time.Time `json:"last_date"`
	LastIndex int64     `json:"last_index"`
}

// Inserts the cover rotation state row if it doesn't exist, otherwise
// updates it in place. The table is constrained to a single row by
// the CHECK (id = 1) clause, so this is the only way to write it.
func (q *Queries) UpsertCoverRotationState(ctx context.Context, arg UpsertCoverRotationStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertCoverRotationState, arg.LastDate, arg.LastIndex)
	return err
}
