// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hat_swaps.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countPendingSwapsForMember = `-- name: CountPendingSwapsForMember :one
SELECT COUNT(*) AS count
FROM hat_swaps
WHERE target_member_id = ? AND status = 'pending'
`

func (q *Queries) CountPendingSwapsForMember(ctx context.Context, targetMemberID string) (int64, error) {
	row := q.db.QueryRowContext(ctx, countPendingSwapsForMember, targetMemberID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHatSwap = `-- name: CreateHatSwap :execresult
INSERT INTO hat_swaps (
    id,
    requester_assignment_id,
    target_assignment_id,
    requester_member_id,
    target_member_id,
    status
) VALUES (?, ?, ?, ?, ?, 'pending')
`

type CreateHatSwapParams struct {
	ID                    string `json:"id"`
	RequesterAssignmentID string `json:"requester_assignment_id"`
	TargetAssignmentID    string `json:"target_assignment_id"`
	RequesterMemberID     string `json:"requester_member_id"`
	TargetMemberID        string `json:"target_member_id"`
}

func (q *Queries) CreateHatSwap(ctx context.Context, arg CreateHatSwapParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createHatSwap,
		arg.ID,
		arg.RequesterAssignmentID,
		arg.TargetAssignmentID,
		arg.RequesterMemberID,
		arg.TargetMemberID,
	)
}

const deleteHatSwap = `-- name: DeleteHatSwap :exec
DELETE FROM hat_swaps
WHERE id = ?
`

func (q *Queries) DeleteHatSwap(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteHatSwap, id)
	return err
}

const getHatSwapByID = `-- name: GetHatSwapByID :one
SELECT id, requester_assignment_id, target_assignment_id,
       requester_member_id, target_member_id, status, created_at, updated_at
FROM hat_swaps
WHERE id = ?
`

func (q *Queries) GetHatSwapByID(ctx context.Context, id string) (HatSwap, error) {
	row := q.db.QueryRowContext(ctx, getHatSwapByID, id)
	var i HatSwap
	err := row.Scan(
		&i.ID,
		&i.RequesterAssignmentID,
		&i.TargetAssignmentID,
		&i.RequesterMemberID,
		&i.TargetMemberID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getOpenSwapForAssignment = `-- name: GetOpenSwapForAssignment :one
SELECT id, requester_assignment_id, target_assignment_id,
       requester_member_id, target_member_id, status, created_at, updated_at
FROM hat_swaps
WHERE (requester_assignment_id = ? OR target_assignment_id = ?)
  AND status = 'pending'
LIMIT 1
`

type GetOpenSwapForAssignmentParams struct {
	RequesterAssignmentID string `json:"requester_assignment_id"`
	TargetAssignmentID    string `json:"target_assignment_id"`
}

func (q *Queries) GetOpenSwapForAssignment(ctx context.Context, arg GetOpenSwapForAssignmentParams) (HatSwap, error) {
	row := q.db.QueryRowContext(ctx, getOpenSwapForAssignment, arg.RequesterAssignmentID, arg.TargetAssignmentID)
	var i HatSwap
	err := row.Scan(
		&i.ID,
		&i.RequesterAssignmentID,
		&i.TargetAssignmentID,
		&i.RequesterMemberID,
		&i.TargetMemberID,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getPendingSwapsForMember = `-- name: GetPendingSwapsForMember :many
SELECT id, requester_assignment_id, target_assignment_id,
       requester_member_id, target_member_id, status, created_at, updated_at
FROM hat_swaps
WHERE target_member_id = ? AND status = 'pending'
ORDER BY created_at DESC
`

func (q *Queries) GetPendingSwapsForMember(ctx context.Context, targetMemberID string) ([]HatSwap, error) {
	rows, err := q.db.QueryContext(ctx, getPendingSwapsForMember, targetMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HatSwap{}
	for rows.Next() {
		var i HatSwap
		if err := rows.Scan(
			&i.ID,
			&i.RequesterAssignmentID,
			&i.TargetAssignmentID,
			&i.RequesterMemberID,
			&i.TargetMemberID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSwapsForMember = `-- name: GetSwapsForMember :many
SELECT id, requester_assignment_id, target_assignment_id,
       requester_member_id, target_member_id, status, created_at, updated_at
FROM hat_swaps
WHERE requester_member_id = ? OR target_member_id = ?
ORDER BY created_at DESC
`

type GetSwapsForMemberParams struct {
	RequesterMemberID string `json:"requester_member_id"`
	TargetMemberID    string `json:"target_member_id"`
}

func (q *Queries) GetSwapsForMember(ctx context.Context, arg GetSwapsForMemberParams) ([]HatSwap, error) {
	rows, err := q.db.QueryContext(ctx, getSwapsForMember, arg.RequesterMemberID, arg.TargetMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HatSwap{}
	for rows.Next() {
		var i HatSwap
		if err := rows.Scan(
			&i.ID,
			&i.RequesterAssignmentID,
			&i.TargetAssignmentID,
			&i.RequesterMemberID,
			&i.TargetMemberID,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHatSwapStatus = `-- name: UpdateHatSwapStatus :exec
UPDATE hat_swaps
SET status = ?, updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateHatSwapStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateHatSwapStatus(ctx context.Context, arg UpdateHatSwapStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateHatSwapStatus, arg.Status, arg.ID)
	return err
}
