// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leave_records.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createLeaveRecord = `-- name: CreateLeaveRecord :execresult
INSERT INTO leave_records (id, member_id, start_date, end_date, status)
VALUES (?, ?, ?, ?, 'pending')
`

type CreateLeaveRecordParams struct {
	ID        string    `json:"id"`
	MemberID  string    `json:"member_id"`
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) CreateLeaveRecord(ctx context.Context, arg CreateLeaveRecordParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createLeaveRecord,
		arg.ID,
		arg.MemberID,
		arg.StartDate,
		arg.EndDate,
	)
}

const getLeaveByDate = `-- name: GetLeaveByDate :many
SELECT id, member_id, start_date, end_date, cover_member_id, status, created_at
FROM leave_records
WHERE ? >= start_date AND ? <= end_date AND status != 'completed'
`

type GetLeaveByDateParams struct {
	StartDate time.Time `json:"start_date"`
	EndDate   time.Time `json:"end_date"`
}

func (q *Queries) GetLeaveByDate(ctx context.Context, arg GetLeaveByDateParams) ([]LeaveRecord, error) {
	rows, err := q.db.QueryContext(ctx, getLeaveByDate, arg.StartDate, arg.EndDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveRecord{}
	for rows.Next() {
		var i LeaveRecord
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.StartDate,
			&i.EndDate,
			&i.CoverMemberID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLeaveByID = `-- name: GetLeaveByID :one
SELECT id, member_id, start_date, end_date, cover_member_id, status, created_at
FROM leave_records
WHERE id = ?
`

func (q *Queries) GetLeaveByID(ctx context.Context, id string) (LeaveRecord, error) {
	row := q.db.QueryRowContext(ctx, getLeaveByID, id)
	var i LeaveRecord
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.StartDate,
		&i.EndDate,
		&i.CoverMemberID,
		&i.Status,
		&i.CreatedAt,
	)
	return i, err
}

const getLeaveRecords = `-- name: GetLeaveRecords :many
SELECT id, member_id, start_date, end_date, cover_member_id, status, created_at
FROM leave_records
WHERE (status = ? OR ? = '')
ORDER BY start_date DESC
`

type GetLeaveRecordsParams struct {
	Status  string      `json:"status"`
	Column2 interface{} `json:"column_2"`
}

func (q *Queries) GetLeaveRecords(ctx context.Context, arg GetLeaveRecordsParams) ([]LeaveRecord, error) {
	rows, err := q.db.QueryContext(ctx, getLeaveRecords, arg.Status, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LeaveRecord{}
	for rows.Next() {
		var i LeaveRecord
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.StartDate,
			&i.EndDate,
			&i.CoverMemberID,
			&i.Status,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeaveCoverMember = `-- name: UpdateLeaveCoverMember :exec
UPDATE leave_records
SET cover_member_id = ?
WHERE id = ?
`

type UpdateLeaveCoverMemberParams struct {
	CoverMemberID sql.NullString `json:"cover_member_id"`
	ID            string         `json:"id"`
}

func (q *Queries) UpdateLeaveCoverMember(ctx context.Context, arg UpdateLeaveCoverMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateLeaveCoverMember, arg.CoverMemberID, arg.ID)
	return err
}

const updateLeaveStatus = `-- name: UpdateLeaveStatus :exec
UPDATE leave_records
SET status = ?
WHERE id = ?
`

type UpdateLeaveStatusParams struct {
	Status string `json:"status"`
	ID     string `json:"id"`
}

func (q *Queries) UpdateLeaveStatus(ctx context.Context, arg UpdateLeaveStatusParams) error {
	_, err := q.db.ExecContext(ctx, updateLeaveStatus, arg.Status, arg.ID)
	return err
}
