// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type CalendarSubscription struct {
	ID        string       `json:"id"`
	MemberID  string       `json:"member_id"`
	Token     string       `json:"token"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type LeaveRecord struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	StartDate     time.Time      `json:"start_date"`
	EndDate       time.Time      `json:"end_date"`
	Type          string         `json:"type"`
	CoverMemberID sql.NullString `json:"cover_member_id"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type RotaAssignment struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	CreatedAt            sql.NullTime   `json:"created_at"`
}

type TeamMember struct {
	ID        string        `json:"id"`
	Name      string        `json:"name"`
	Email     string        `json:"email"`
	IsActive  sql.NullInt64 `json:"is_active"`
	CreatedAt sql.NullTime  `json:"created_at"`
}
