// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Name       string        `json:"name"`
	TokenHash  string        `json:"token_hash"`
	IsActive   sql.NullInt64 `json:"is_active"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	ExpiresAt  sql.NullTime  `json:"expires_at"`
	LastUsedAt sql.NullTime  `json:"last_used_at"`
}

type CalendarSubscription struct {
	ID                 string       `json:"id"`
	MemberID           string       `json:"member_id"`
	Token              string       `json:"token"`
	CreatedAt          sql.NullTime `json:"created_at"`
	LastUsedAt         sql.NullTime `json:"last_used_at"`
	LastUsedRotaAt     sql.NullTime `json:"last_used_rota_at"`
	LastUsedMeetingsAt sql.NullTime `json:"last_used_meetings_at"`
}

type HatSwap struct {
	ID                    string       `json:"id"`
	RequesterAssignmentID string       `json:"requester_assignment_id"`
	TargetAssignmentID    string       `json:"target_assignment_id"`
	RequesterMemberID     string       `json:"requester_member_id"`
	TargetMemberID        string       `json:"target_member_id"`
	Status                string       `json:"status"`
	CreatedAt             sql.NullTime `json:"created_at"`
	UpdatedAt             sql.NullTime `json:"updated_at"`
}

type LeaveRecord struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	StartDate     time.Time      `json:"start_date"`
	EndDate       time.Time      `json:"end_date"`
	CoverMemberID sql.NullString `json:"cover_member_id"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type OauthToken struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	TokenType    sql.NullString `json:"token_type"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type RotaAssignment struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
	CreatedAt            sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type TeamMember struct {
	ID             string        `json:"id"`
	Name           string        `json:"name"`
	Email          string        `json:"email"`
	IsActive       sql.NullInt64 `json:"is_active"`
	IsPermanentWfh int64         `json:"is_permanent_wfh"`
	CreatedAt      sql.NullTime  `json:"created_at"`
}

type User struct {
	ID         string        `json:"id"`
	Email      string        `json:"email"`
	Name       string        `json:"name"`
	Provider   string        `json:"provider"`
	ProviderID string        `json:"provider_id"`
	IsAdmin    sql.NullInt64 `json:"is_admin"`
	IsActive   sql.NullInt64 `json:"is_active"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	UpdatedAt  sql.NullTime  `json:"updated_at"`
}

type WfhRequest struct {
	ID          string         `json:"id"`
	MemberID    string         `json:"member_id"`
	Date        time.Time      `json:"date"`
	Status      string         `json:"status"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	SettledAt   sql.NullTime   `json:"settled_at"`
	WithdrawnBy sql.NullString `json:"withdrawn_by"`
	WithdrawnAt sql.NullTime   `json:"withdrawn_at"`
}
