// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"database/sql"
	"time"
)

type ApiToken struct {
	ID         string        `json:"id"`
	UserID     string        `json:"user_id"`
	Name       string        `json:"name"`
	TokenHash  string        `json:"token_hash"`
	IsActive   sql.NullInt64 `json:"is_active"`
	CreatedAt  sql.NullTime  `json:"created_at"`
	ExpiresAt  sql.NullTime  `json:"expires_at"`
	LastUsedAt sql.NullTime  `json:"last_used_at"`
}

type CalendarSubscription struct {
	ID                 string       `json:"id"`
	MemberID           string       `json:"member_id"`
	Token              string       `json:"token"`
	CreatedAt          sql.NullTime `json:"created_at"`
	LastUsedAt         sql.NullTime `json:"last_used_at"`
	LastUsedRotaAt     sql.NullTime `json:"last_used_rota_at"`
	LastUsedMeetingsAt sql.NullTime `json:"last_used_meetings_at"`
}

type CoverRotationState struct {
	ID                int64         `json:"id"`
	LastDate          time.Time     `json:"last_date"`
	LastIndex         int64         `json:"last_index"`
	LastReassignDate  sql.NullTime  `json:"last_reassign_date"`
	LastReassignIndex sql.NullInt64 `json:"last_reassign_index"`
}

type HatSwap struct {
	ID                    string       `json:"id"`
	RequesterAssignmentID string       `json:"requester_assignment_id"`
	TargetAssignmentID    string       `json:"target_assignment_id"`
	RequesterMemberID     string       `json:"requester_member_id"`
	TargetMemberID        string       `json:"target_member_id"`
	Status                string       `json:"status"`
	CreatedAt             sql.NullTime `json:"created_at"`
	UpdatedAt             sql.NullTime `json:"updated_at"`
}

type LeaveRecord struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	StartDate     time.Time      `json:"start_date"`
	EndDate       time.Time      `json:"end_date"`
	CoverMemberID sql.NullString `json:"cover_member_id"`
	Status        string         `json:"status"`
	LeaveType     string         `json:"leave_type"`
	CreatedAt     sql.NullTime   `json:"created_at"`
}

type NotificationOutbox struct {
	ID             string         `json:"id"`
	EventKind      string         `json:"event_kind"`
	Channel        string         `json:"channel"`
	Recipient      string         `json:"recipient"`
	RecipientName  sql.NullString `json:"recipient_name"`
	Subject        string         `json:"subject"`
	Body           string         `json:"body"`
	UnsubscribeUrl sql.NullString `json:"unsubscribe_url"`
	Attempts       int64          `json:"attempts"`
	LastError      sql.NullString `json:"last_error"`
	NextAttemptAt  time.Time      `json:"next_attempt_at"`
	Status         string         `json:"status"`
	CreatedAt      time.Time      `json:"created_at"`
	SentAt         sql.NullTime   `json:"sent_at"`
}

type NotificationPreference struct {
	MemberID     string       `json:"member_id"`
	EmailEnabled int64        `json:"email_enabled"`
	DisabledAt   sql.NullTime `json:"disabled_at"`
	UpdatedAt    time.Time    `json:"updated_at"`
}

type OauthToken struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	TokenType    sql.NullString `json:"token_type"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	CreatedAt    sql.NullTime   `json:"created_at"`
	UpdatedAt    sql.NullTime   `json:"updated_at"`
}

type R1RotationState struct {
	LastDate  time.Time `json:"last_date"`
	LastIndex int64     `json:"last_index"`
}

type RotaAssignment struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
	CreatedAt            sql.NullTime   `json:"created_at"`
}

type Session struct {
	ID        string       `json:"id"`
	UserID    string       `json:"user_id"`
	Token     string       `json:"token"`
	ExpiresAt time.Time    `json:"expires_at"`
	CreatedAt sql.NullTime `json:"created_at"`
}

type TeamMember struct {
	ID                     string        `json:"id"`
	Name                   string        `json:"name"`
	Email                  string        `json:"email"`
	IsActive               sql.NullInt64 `json:"is_active"`
	IsPermanentWfh         int64         `json:"is_permanent_wfh"`
	IsExemptFromAssignment int64         `json:"is_exempt_from_assignment"`
	RecurringWfhMonday     int64         `json:"recurring_wfh_monday"`
	RecurringWfhTuesday    int64         `json:"recurring_wfh_tuesday"`
	RecurringWfhWednesday  int64         `json:"recurring_wfh_wednesday"`
	RecurringWfhThursday   int64         `json:"recurring_wfh_thursday"`
	RecurringWfhFriday     int64         `json:"recurring_wfh_friday"`
	CreatedAt              sql.NullTime  `json:"created_at"`
}

type User struct {
	ID            string        `json:"id"`
	Email         string        `json:"email"`
	Name          string        `json:"name"`
	Provider      string        `json:"provider"`
	ProviderID    string        `json:"provider_id"`
	IsAdmin       sql.NullInt64 `json:"is_admin"`
	IsActive      sql.NullInt64 `json:"is_active"`
	DeactivatedAt sql.NullTime  `json:"deactivated_at"`
	CreatedAt     sql.NullTime  `json:"created_at"`
	UpdatedAt     sql.NullTime  `json:"updated_at"`
}

type WfhAssignmentSwap struct {
	ID                    string       `json:"id"`
	RequesterWfhRequestID string       `json:"requester_wfh_request_id"`
	TargetMemberID        string       `json:"target_member_id"`
	SwapDate              time.Time    `json:"swap_date"`
	Status                string       `json:"status"`
	CreatedAt             sql.NullTime `json:"created_at"`
	UpdatedAt             sql.NullTime `json:"updated_at"`
	ResolvedAt            sql.NullTime `json:"resolved_at"`
}

type WfhCoPresence struct {
	CoPresenceID string    `json:"co_presence_id"`
	WorkingDate  time.Time `json:"working_date"`
	MemberIDA    string    `json:"member_id_a"`
	MemberIDB    string    `json:"member_id_b"`
	RecordedAt   time.Time `json:"recorded_at"`
}

type WfhRequest struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	Origin        string         `json:"origin"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
}
