// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_preferences.sql

package sqlc

import (
	"context"
	"database/sql"
)

const getNotificationPreference = `-- name: GetNotificationPreference :one
SELECT member_id, email_enabled, disabled_at, updated_at
FROM notification_preferences
WHERE member_id = ?
`

// Returns the row for a member, or sql.ErrNoRows if no preference
// has been set. The application treats the absence of a row as
// "default" (email_enabled = 1).
func (q *Queries) GetNotificationPreference(ctx context.Context, memberID string) (NotificationPreference, error) {
	row := q.db.QueryRowContext(ctx, getNotificationPreference, memberID)
	var i NotificationPreference
	err := row.Scan(
		&i.MemberID,
		&i.EmailEnabled,
		&i.DisabledAt,
		&i.UpdatedAt,
	)
	return i, err
}

const isNotificationEmailEnabled = `-- name: IsNotificationEmailEnabled :one
SELECT COALESCE(
    (SELECT CASE WHEN email_enabled = 0 THEN 0 ELSE 1 END
     FROM notification_preferences
     WHERE member_id = ?),
    1
) AS is_enabled
`

// Returns 1 when the member has not disabled email, 0 when they
// have. Returns 1 by default (no row) so callers don't have to
// special-case "no preference set yet". The query is a single
// parameter and a single scan, so the no-row case still produces
// one row from the COALESCE branch.
func (q *Queries) IsNotificationEmailEnabled(ctx context.Context, memberID string) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, isNotificationEmailEnabled, memberID)
	var is_enabled interface{}
	err := row.Scan(&is_enabled)
	return is_enabled, err
}

const setNotificationEmailEnabled = `-- name: SetNotificationEmailEnabled :exec
INSERT INTO notification_preferences (member_id, email_enabled, disabled_at, updated_at)
VALUES (?, ?, ?, CURRENT_TIMESTAMP)
ON CONFLICT (member_id) DO UPDATE SET
    email_enabled = excluded.email_enabled,
    disabled_at   = excluded.disabled_at,
    updated_at    = CURRENT_TIMESTAMP
`

type SetNotificationEmailEnabledParams struct {
	MemberID     string       `json:"member_id"`
	EmailEnabled int64        `json:"email_enabled"`
	DisabledAt   sql.NullTime `json:"disabled_at"`
}

// Upserts the email-enabled flag for a member. Pass 1 to enable,
// 0 to disable. disabled_at is set/cleared by the application
// before calling this query.
func (q *Queries) SetNotificationEmailEnabled(ctx context.Context, arg SetNotificationEmailEnabledParams) error {
	_, err := q.db.ExecContext(ctx, setNotificationEmailEnabled, arg.MemberID, arg.EmailEnabled, arg.DisabledAt)
	return err
}
