// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: notification_outbox.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const claimDueOutboxEntries = `-- name: ClaimDueOutboxEntries :many
SELECT id, event_kind, channel, recipient, recipient_name, subject, body, unsubscribe_url,
       attempts, last_error, next_attempt_at, status, created_at, sent_at
FROM notification_outbox
WHERE status = 'pending'
  AND datetime(next_attempt_at) <= datetime('now')
ORDER BY next_attempt_at
LIMIT ?
`

// Atomically claim a batch of due rows by bumping next_attempt_at far into
// the future, so concurrent workers don't pick the same row.
//
// The datetime() wrapper normalises the stored ISO-8601 value (which the
// ncruces/go-sqlite3 driver writes for time.Time arguments) into the
// same YYYY-MM-DD HH:MM:SS form that datetime('now') returns, so the
// comparison is meaningful. Without this normalisation SQLite compares
// strings and 'T' > ' ' lexically, so no row would ever be due.
func (q *Queries) ClaimDueOutboxEntries(ctx context.Context, limit int64) ([]NotificationOutbox, error) {
	rows, err := q.db.QueryContext(ctx, claimDueOutboxEntries, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []NotificationOutbox{}
	for rows.Next() {
		var i NotificationOutbox
		if err := rows.Scan(
			&i.ID,
			&i.EventKind,
			&i.Channel,
			&i.Recipient,
			&i.RecipientName,
			&i.Subject,
			&i.Body,
			&i.UnsubscribeUrl,
			&i.Attempts,
			&i.LastError,
			&i.NextAttemptAt,
			&i.Status,
			&i.CreatedAt,
			&i.SentAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createOutboxEntry = `-- name: CreateOutboxEntry :execresult
INSERT INTO notification_outbox (
    id, event_kind, channel, recipient, recipient_name, subject, body, unsubscribe_url
) VALUES (?, ?, ?, ?, ?, ?, ?, ?)
`

type CreateOutboxEntryParams struct {
	ID             string         `json:"id"`
	EventKind      string         `json:"event_kind"`
	Channel        string         `json:"channel"`
	Recipient      string         `json:"recipient"`
	RecipientName  sql.NullString `json:"recipient_name"`
	Subject        string         `json:"subject"`
	Body           string         `json:"body"`
	UnsubscribeUrl sql.NullString `json:"unsubscribe_url"`
}

func (q *Queries) CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createOutboxEntry,
		arg.ID,
		arg.EventKind,
		arg.Channel,
		arg.Recipient,
		arg.RecipientName,
		arg.Subject,
		arg.Body,
		arg.UnsubscribeUrl,
	)
}

const getOutboxEntry = `-- name: GetOutboxEntry :one
SELECT id, event_kind, channel, recipient, recipient_name, subject, body, unsubscribe_url,
       attempts, last_error, next_attempt_at, status, created_at, sent_at
FROM notification_outbox
WHERE id = ?
`

func (q *Queries) GetOutboxEntry(ctx context.Context, id string) (NotificationOutbox, error) {
	row := q.db.QueryRowContext(ctx, getOutboxEntry, id)
	var i NotificationOutbox
	err := row.Scan(
		&i.ID,
		&i.EventKind,
		&i.Channel,
		&i.Recipient,
		&i.RecipientName,
		&i.Subject,
		&i.Body,
		&i.UnsubscribeUrl,
		&i.Attempts,
		&i.LastError,
		&i.NextAttemptAt,
		&i.Status,
		&i.CreatedAt,
		&i.SentAt,
	)
	return i, err
}

const markOutboxDead = `-- name: MarkOutboxDead :execresult
UPDATE notification_outbox
SET status = 'dead', attempts = attempts + 1,
    last_error = ?, next_attempt_at = ?
WHERE id = ?
`

type MarkOutboxDeadParams struct {
	LastError     sql.NullString `json:"last_error"`
	NextAttemptAt time.Time      `json:"next_attempt_at"`
	ID            string         `json:"id"`
}

func (q *Queries) MarkOutboxDead(ctx context.Context, arg MarkOutboxDeadParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markOutboxDead, arg.LastError, arg.NextAttemptAt, arg.ID)
}

const markOutboxFailed = `-- name: MarkOutboxFailed :execresult
UPDATE notification_outbox
SET attempts = attempts + 1,
    last_error = ?,
    next_attempt_at = ?
WHERE id = ?
`

type MarkOutboxFailedParams struct {
	LastError     sql.NullString `json:"last_error"`
	NextAttemptAt time.Time      `json:"next_attempt_at"`
	ID            string         `json:"id"`
}

func (q *Queries) MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markOutboxFailed, arg.LastError, arg.NextAttemptAt, arg.ID)
}

const markOutboxSent = `-- name: MarkOutboxSent :execresult
UPDATE notification_outbox
SET status = 'sent', sent_at = CURRENT_TIMESTAMP, last_error = NULL
WHERE id = ?
`

func (q *Queries) MarkOutboxSent(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, markOutboxSent, id)
}
