// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: notification_logs.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createNotificationLog = `-- name: CreateNotificationLog :execrows

INSERT OR IGNORE INTO notification_logs (
  id,
  kind,
  date,
  member_id,
  assignment_id,
  message
) VALUES (?, ?, ?, ?, ?, ?)
`

type CreateNotificationLogParams struct {
	ID           string         `json:"id"`
	Kind         string         `json:"kind"`
	Date         time.Time      `json:"date"`
	MemberID     sql.NullString `json:"member_id"`
	AssignmentID sql.NullString `json:"assignment_id"`
	Message      sql.NullString `json:"message"`
}

// Notification logs
func (q *Queries) CreateNotificationLog(ctx context.Context, arg CreateNotificationLogParams) (int64, error) {
	result, err := q.db.ExecContext(ctx, createNotificationLog,
		arg.ID,
		arg.Kind,
		arg.Date,
		arg.MemberID,
		arg.AssignmentID,
		arg.Message,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected()
}

const deleteNotificationLog = `-- name: DeleteNotificationLog :exec
DELETE FROM notification_logs WHERE id = ?
`

func (q *Queries) DeleteNotificationLog(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteNotificationLog, id)
	return err
}
