// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: oauth_tokens.sql

package sqlc

import (
	"context"
	"database/sql"
)

const createOAuthToken = `-- name: CreateOAuthToken :one
INSERT INTO oauth_tokens (
    id, user_id, provider, access_token, refresh_token, token_type, expires_at
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, user_id, provider, access_token, refresh_token, token_type, expires_at, created_at, updated_at
`

type CreateOAuthTokenParams struct {
	ID           string         `json:"id"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	TokenType    sql.NullString `json:"token_type"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
}

func (q *Queries) CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, createOAuthToken,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.ExpiresAt,
	)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteOAuthToken = `-- name: DeleteOAuthToken :exec
DELETE FROM oauth_tokens
WHERE user_id = ? AND provider = ?
`

type DeleteOAuthTokenParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, deleteOAuthToken, arg.UserID, arg.Provider)
	return err
}

const deleteUserOAuthTokens = `-- name: DeleteUserOAuthTokens :exec
DELETE FROM oauth_tokens
WHERE user_id = ?
`

func (q *Queries) DeleteUserOAuthTokens(ctx context.Context, userID string) error {
	_, err := q.db.ExecContext(ctx, deleteUserOAuthTokens, userID)
	return err
}

const getOAuthToken = `-- name: GetOAuthToken :one
SELECT id, user_id, provider, access_token, refresh_token, token_type, expires_at, created_at, updated_at FROM oauth_tokens 
WHERE user_id = ? AND provider = ? 
LIMIT 1
`

type GetOAuthTokenParams struct {
	UserID   string `json:"user_id"`
	Provider string `json:"provider"`
}

func (q *Queries) GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error) {
	row := q.db.QueryRowContext(ctx, getOAuthToken, arg.UserID, arg.Provider)
	var i OauthToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.AccessToken,
		&i.RefreshToken,
		&i.TokenType,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateOAuthToken = `-- name: UpdateOAuthToken :exec
UPDATE oauth_tokens 
SET 
    access_token = ?,
    refresh_token = ?,
    token_type = ?,
    expires_at = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE user_id = ? AND provider = ?
`

type UpdateOAuthTokenParams struct {
	AccessToken  string         `json:"access_token"`
	RefreshToken sql.NullString `json:"refresh_token"`
	TokenType    sql.NullString `json:"token_type"`
	ExpiresAt    sql.NullTime   `json:"expires_at"`
	UserID       string         `json:"user_id"`
	Provider     string         `json:"provider"`
}

func (q *Queries) UpdateOAuthToken(ctx context.Context, arg UpdateOAuthTokenParams) error {
	_, err := q.db.ExecContext(ctx, updateOAuthToken,
		arg.AccessToken,
		arg.RefreshToken,
		arg.TokenType,
		arg.ExpiresAt,
		arg.UserID,
		arg.Provider,
	)
	return err
}
