// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	ActivateTeamMember(ctx context.Context, id string) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (sql.Result, error)
	// Activates a pending user. The deactivated_at column stays NULL
	// (it was NULL while pending and is cleared on approve).
	ApproveUser(ctx context.Context, id string) (User, error)
	// Auto-cancel pass run by SettlePendingRequests (step 15
	// of plans/assigned-wfh-plan.md): flips every pending swap
	// whose swap_date is strictly before today to status=
	// 'cancelled'. The idx_wfh_assignment_swaps_date index
	// covers this; the cutoff is computed in Go as today.
	CancelExpiredSwaps(ctx context.Context, swapDate time.Time) (sql.Result, error)
	// Atomically claim a batch of due rows by bumping next_attempt_at far into
	// the future, so concurrent workers don't pick the same row.
	//
	// The datetime() wrapper normalises the stored ISO-8601 value (which the
	// ncruces/go-sqlite3 driver writes for time.Time arguments) into the
	// same YYYY-MM-DD HH:MM:SS form that datetime('now') returns, so the
	// comparison is meaningful. Without this normalisation SQLite compares
	// strings and 'T' > ' ' lexically, so no row would ever be due.
	ClaimDueOutboxEntries(ctx context.Context, limit int64) ([]NotificationOutbox, error)
	CleanupExpiredTokens(ctx context.Context) (sql.Result, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountApprovedWFHByDate(ctx context.Context, date time.Time) (int64, error)
	CountPendingSwapsForMember(ctx context.Context, targetMemberID string) (int64, error)
	CountPendingUsers(ctx context.Context) (int64, error)
	CountWFHRequestsBefore(ctx context.Context, date time.Time) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (sql.Result, error)
	// Inserts an already-active user. Used by test fixtures and the
	// dev-mode seeder; the production OAuth flow goes through
	// CreateUser (pending) and is approved by an admin.
	CreateActiveUser(ctx context.Context, arg CreateActiveUserParams) (User, error)
	CreateApprovedAssignedWFHRequest(ctx context.Context, arg CreateApprovedAssignedWFHRequestParams) (sql.Result, error)
	CreateApprovedRecurringWFHRequest(ctx context.Context, arg CreateApprovedRecurringWFHRequestParams) (sql.Result, error)
	CreateCalendarSubscription(ctx context.Context, arg CreateCalendarSubscriptionParams) (sql.Result, error)
	CreateHatSwap(ctx context.Context, arg CreateHatSwapParams) (sql.Result, error)
	CreateLeaveRecord(ctx context.Context, arg CreateLeaveRecordParams) (sql.Result, error)
	CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error)
	CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (sql.Result, error)
	CreateRotaAssignment(ctx context.Context, arg CreateRotaAssignmentParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	// Insert a new pending swap request. Caller is responsible
	// for the 409-conflict check (any pending swap for the same
	// requester_wfh_request_id); the application enforces it
	// before calling this query.
	CreateSwap(ctx context.Context, arg CreateSwapParams) (sql.Result, error)
	// Inserts a user as pending (is_active = 0). The first-ever
	// user is bootstrapped via CreateUserAsFirstAdmin instead, which
	// sets is_active = 1 atomically.
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Atomically creates a user and makes them admin only if no admins
	// exist. The first-ever user is bootstrapped active (is_active = 1)
	// so the operator can log in; every subsequent user is pending
	// (is_active = 0) and requires admin approval.
	CreateUserAsFirstAdmin(ctx context.Context, arg CreateUserAsFirstAdminParams) (User, error)
	// Mark a request as denied and record the human-readable reason in
	// wfh_requests.denial_reason. The reason rides the same row to
	// the dashboard, the WFH list page, the admin manage page, and
	// the email notification so the user is never left guessing why their
	// request was rejected.
	CreateWFHRequest(ctx context.Context, arg CreateWFHRequestParams) (sql.Result, error)
	DeactivateAPIToken(ctx context.Context, id string) (sql.Result, error)
	DeactivateTeamMember(ctx context.Context, id string) error
	// Admin-initiated deactivation of an active user. Sets
	// deactivated_at; the team page can offer reactivate from this
	// state.
	DeactivateUser(ctx context.Context, id string) (User, error)
	DeleteAPIToken(ctx context.Context, id string) (sql.Result, error)
	DeleteAssignmentsByDateRange(ctx context.Context, arg DeleteAssignmentsByDateRangeParams) error
	DeleteCalendarSubscription(ctx context.Context, token string) error
	DeleteExpiredLeaveRecords(ctx context.Context, endDate time.Time) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteHatSwap(ctx context.Context, id string) error
	DeleteLeaveRecord(ctx context.Context, id string) error
	DeleteMemberSubscriptions(ctx context.Context, memberID string) error
	DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error
	DeleteRotaAssignment(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, token string) error
	DeleteStaleSubscriptions(ctx context.Context, arg DeleteStaleSubscriptionsParams) (sql.Result, error)
	DeleteTeamMember(ctx context.Context, id string) error
	DeleteUser(ctx context.Context, id string) error
	DeleteUserOAuthTokens(ctx context.Context, userID string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	DeleteWFHRequest(ctx context.Context, id string) error
	DenyWFHRequest(ctx context.Context, arg DenyWFHRequestParams) (sql.Result, error)
	// INSERT-OR-IGNORE the single row of cover_rotation_state. Used by
	// the reassign path so its subsequent UPDATE does not fail on a
	// fresh database where the row does not exist yet. Only the id is
	// inserted; the ad-hoc columns stay NULL (or whatever a prior
	// ad-hoc HandleLeaveChange left them as) and the reassign columns
	// are populated by the subsequent UPDATE.
	EnsureReassignmentAnchorRow(ctx context.Context) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAPITokenByID(ctx context.Context, id string) (ApiToken, error)
	GetAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error)
	GetActiveTeamMembers(ctx context.Context) ([]TeamMember, error)
	GetAllSubscriptions(ctx context.Context) ([]CalendarSubscription, error)
	GetAllWFHRequests(ctx context.Context) ([]GetAllWFHRequestsRow, error)
	GetAssignmentByID(ctx context.Context, id string) (GetAssignmentByIDRow, error)
	GetAssignmentsByDate(ctx context.Context, date time.Time) ([]GetAssignmentsByDateRow, error)
	GetAssignmentsByDateRange(ctx context.Context, arg GetAssignmentsByDateRangeParams) ([]GetAssignmentsByDateRangeRow, error)
	GetCoverAssignmentByDate(ctx context.Context, date time.Time) (GetCoverAssignmentByDateRow, error)
	// Returns the single row of the cover_rotation_state table, or
	// sql.ErrNoRows if no state has been written yet (a fresh database
	// has no row until the first cover is computed).
	GetCoverRotationState(ctx context.Context) (GetCoverRotationStateRow, error)
	GetFutureAssignments(ctx context.Context) ([]GetFutureAssignmentsRow, error)
	GetFutureAssignmentsForMember(ctx context.Context, memberID string) ([]GetFutureAssignmentsForMemberRow, error)
	GetHatSwapByID(ctx context.Context, id string) (HatSwap, error)
	GetLatestAssignmentDate(ctx context.Context) (interface{}, error)
	GetLatestCoPresenceWithCohortA(ctx context.Context, arg GetLatestCoPresenceWithCohortAParams) ([]time.Time, error)
	GetLatestCoPresenceWithCohortB(ctx context.Context, arg GetLatestCoPresenceWithCohortBParams) ([]time.Time, error)
	GetLeaveByDate(ctx context.Context, arg GetLeaveByDateParams) ([]LeaveRecord, error)
	GetLeaveByID(ctx context.Context, id string) (LeaveRecord, error)
	GetLeaveRecords(ctx context.Context, arg GetLeaveRecordsParams) ([]LeaveRecord, error)
	GetMemberByEmail(ctx context.Context, email string) (TeamMember, error)
	GetMemberByID(ctx context.Context, id string) (TeamMember, error)
	GetMemberByToken(ctx context.Context, token string) (TeamMember, error)
	// Returns the row for a member, or sql.ErrNoRows if no preference
	// has been set. The application treats the absence of a row as
	// "default" (email_enabled = 1).
	GetNotificationPreference(ctx context.Context, memberID string) (NotificationPreference, error)
	GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error)
	GetOpenSwapForAssignment(ctx context.Context, arg GetOpenSwapForAssignmentParams) (HatSwap, error)
	GetOutboxEntry(ctx context.Context, id string) (NotificationOutbox, error)
	// 409-conflict guard: returns the pending swap for a given
	// assigned wfh_request row, if any. nil when no pending
	// swap exists. Used in handleWFHSwapCreate before the
	// INSERT to enforce "one pending swap per assigned row".
	GetPendingSwapForRequesterRow(ctx context.Context, requesterWfhRequestID string) (WfhAssignmentSwap, error)
	GetPendingSwapsForMember(ctx context.Context, targetMemberID string) ([]HatSwap, error)
	// Outbound read for the requester. Returns all swaps the
	// current member has opened that are still pending. Used
	// by the swap form to show "your swap is awaiting N's
	// decision" and by the cancel button.
	GetPendingSwapsForRequester(ctx context.Context, memberID string) ([]WfhAssignmentSwap, error)
	// Inbox read for the target member. Returns all swaps where
	// the target is the current user and status='pending'. The
	// idx_wfh_assignment_swaps_target index covers this.
	GetPendingSwapsForTarget(ctx context.Context, targetMemberID string) ([]WfhAssignmentSwap, error)
	GetPendingWFHRequestsForSettlement(ctx context.Context, date time.Time) ([]GetPendingWFHRequestsForSettlementRow, error)
	// Returns the R1 (original-HAT) rotation state, or sql.ErrNoRows
	// if no R1 assignment has been written yet. The R1 rotation is
	// kept in its own table (r1_rotation_state) so its write rules
	// (only advance on successful assignment write) don't collide
	// with the cover rotation's write rules (advance on every
	// computation).
	GetR1RotationState(ctx context.Context) (R1RotationState, error)
	// Reads the ReassignCovers-only anchor. Returns sql.ErrNoRows if the
	// row has never been written, which signals a fresh database.
	GetReassignmentAnchor(ctx context.Context) (GetReassignmentAnchorRow, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetSubscriptionByToken(ctx context.Context, token string) (CalendarSubscription, error)
	GetSubscriptionsByMemberID(ctx context.Context, memberID string) ([]CalendarSubscription, error)
	GetSwapByID(ctx context.Context, id string) (WfhAssignmentSwap, error)
	GetSwapsForMember(ctx context.Context, arg GetSwapsForMemberParams) ([]HatSwap, error)
	GetUpcomingAssignments(ctx context.Context, arg GetUpcomingAssignmentsParams) ([]GetUpcomingAssignmentsRow, error)
	GetUpcomingWFHForMember(ctx context.Context, arg GetUpcomingWFHForMemberParams) ([]GetUpcomingWFHForMemberRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error)
	GetWFHRequestByID(ctx context.Context, id string) (GetWFHRequestByIDRow, error)
	GetWFHRequestByMemberAndDate(ctx context.Context, arg GetWFHRequestByMemberAndDateParams) (GetWFHRequestByMemberAndDateRow, error)
	GetWFHRequestsByDate(ctx context.Context, date time.Time) ([]GetWFHRequestsByDateRow, error)
	GetWFHRequestsByDateAndStatus(ctx context.Context, arg GetWFHRequestsByDateAndStatusParams) ([]GetWFHRequestsByDateAndStatusRow, error)
	GetWFHRequestsByMember(ctx context.Context, memberID string) ([]GetWFHRequestsByMemberRow, error)
	GetWFHRequestsByMemberAndPeriod(ctx context.Context, arg GetWFHRequestsByMemberAndPeriodParams) ([]GetWFHRequestsByMemberAndPeriodRow, error)
	GetWFHRequestsVoluntaryInPeriod(ctx context.Context, arg GetWFHRequestsVoluntaryInPeriodParams) ([]GetWFHRequestsVoluntaryInPeriodRow, error)
	IsAdminMarkedWFH(ctx context.Context, arg IsAdminMarkedWFHParams) (int64, error)
	// Returns 1 when the member has not disabled email, 0 when they
	// have. Returns 1 by default (no row) so callers don't have to
	// special-case "no preference set yet". The query is a single
	// parameter and a single scan, so the no-row case still produces
	// one row from the COALESCE branch.
	IsNotificationEmailEnabled(ctx context.Context, memberID string) (interface{}, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListAdminUsers(ctx context.Context) ([]User, error)
	ListDeactivatedUsers(ctx context.Context) ([]User, error)
	// Users awaiting admin approval. Excludes admin-deactivated
	// users (those have deactivated_at set).
	ListPendingUsers(ctx context.Context) ([]User, error)
	MarkAdminWFH(ctx context.Context, arg MarkAdminWFHParams) (sql.Result, error)
	MarkAssignmentSwapped(ctx context.Context, id string) error
	MarkOutboxDead(ctx context.Context, arg MarkOutboxDeadParams) (sql.Result, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (sql.Result, error)
	MarkOutboxSent(ctx context.Context, id string) (sql.Result, error)
	PruneCoPresenceOlderThan(ctx context.Context, workingDate time.Time) (sql.Result, error)
	PurgeWFHRequestsBefore(ctx context.Context, date time.Time) (sql.Result, error)
	ReactivateUser(ctx context.Context, id string) (User, error)
	RecordWFHCoPresencePair(ctx context.Context, arg RecordWFHCoPresencePairParams) (sql.Result, error)
	ResurrectWFHRequest(ctx context.Context, id string) (sql.Result, error)
	// Upserts the email-enabled flag for a member. Pass 1 to enable,
	// 0 to disable. disabled_at is set/cleared by the application
	// before calling this query.
	SetNotificationEmailEnabled(ctx context.Context, arg SetNotificationEmailEnabledParams) error
	// Toggle the seat-cap-picker exemption. Mirrors SetTeamMemberPermanentWFH
	// (also an :exec UPDATE) so the team-member-edit admin form can call
	// both setters side-by-side. The picker reads this flag in step 6.
	SetTeamMemberExemptFromAssignment(ctx context.Context, arg SetTeamMemberExemptFromAssignmentParams) error
	SetTeamMemberPermanentWFH(ctx context.Context, arg SetTeamMemberPermanentWFHParams) error
	SetTeamMemberRecurringWFHDays(ctx context.Context, arg SetTeamMemberRecurringWFHDaysParams) error
	TouchMeetingsSubscription(ctx context.Context, token string) error
	TouchRotaSubscription(ctx context.Context, token string) error
	UpdateAPITokenLastUsed(ctx context.Context, id string) (sql.Result, error)
	UpdateAssignmentMember(ctx context.Context, arg UpdateAssignmentMemberParams) error
	UpdateCoverMember(ctx context.Context, arg UpdateCoverMemberParams) error
	UpdateHatSwapStatus(ctx context.Context, arg UpdateHatSwapStatusParams) (sql.Result, error)
	UpdateLeaveCoverMember(ctx context.Context, arg UpdateLeaveCoverMemberParams) error
	UpdateLeaveRecord(ctx context.Context, arg UpdateLeaveRecordParams) error
	UpdateLeaveStatus(ctx context.Context, arg UpdateLeaveStatusParams) error
	UpdateOAuthToken(ctx context.Context, arg UpdateOAuthTokenParams) error
	// Updates the reassign anchor columns only. Does not touch the
	// ad-hoc last_date / last_index columns, so a concurrent ad-hoc
	// HandleLeaveChange is safe. The reassign path never reads or
	// writes the ad-hoc state.
	UpdateReassignmentAnchor(ctx context.Context, arg UpdateReassignmentAnchorParams) error
	// State transition for accept / reject / cancel. Caller
	// passes the new status string and a resolved_at
	// timestamp. status='cancelled' is used by both the requester
	// (voluntary) and the scheduler (auto-cancel because the
	// date passed).
	UpdateSwapStatus(ctx context.Context, arg UpdateSwapStatusParams) (sql.Result, error)
	UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) error
	UpdateWFHRequestStatus(ctx context.Context, arg UpdateWFHRequestStatusParams) (sql.Result, error)
	UpdateWFHRequestWithdrawn(ctx context.Context, arg UpdateWFHRequestWithdrawnParams) (sql.Result, error)
	// Inserts the cover rotation state row if it doesn't exist, otherwise
	// updates it in place. The table is constrained to a single row by
	// the CHECK (id = 1) clause, so this is the only way to write it.
	UpsertCoverRotationState(ctx context.Context, arg UpsertCoverRotationStateParams) error
	// Writes the R1 rotation state. The table holds at most one
	// row, so this either inserts the first row or replaces the
	// existing one. R1 is keyed by the (date, index) pair of the
	// most recently written original assignment.
	UpsertR1RotationState(ctx context.Context, arg UpsertR1RotationStateParams) error
}

var _ Querier = (*Queries)(nil)
