// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

type Querier interface {
	ActivateTeamMember(ctx context.Context, id string) error
	AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (sql.Result, error)
	// Atomically claim a batch of due rows by bumping next_attempt_at far into
	// the future, so concurrent workers don't pick the same row.
	//
	// The datetime() wrapper normalises the stored ISO-8601 value (which the
	// ncruces/go-sqlite3 driver writes for time.Time arguments) into the
	// same YYYY-MM-DD HH:MM:SS form that datetime('now') returns, so the
	// comparison is meaningful. Without this normalisation SQLite compares
	// strings and 'T' > ' ' lexically, so no row would ever be due.
	ClaimDueOutboxEntries(ctx context.Context, limit int64) ([]NotificationOutbox, error)
	CleanupExpiredTokens(ctx context.Context) (sql.Result, error)
	CountAdmins(ctx context.Context) (int64, error)
	CountApprovedWFHByDate(ctx context.Context, date time.Time) (int64, error)
	CountPendingSwapsForMember(ctx context.Context, targetMemberID string) (int64, error)
	CreateAPIToken(ctx context.Context, arg CreateAPITokenParams) (sql.Result, error)
	CreateApprovedRecurringWFHRequest(ctx context.Context, arg CreateApprovedRecurringWFHRequestParams) (sql.Result, error)
	CreateCalendarSubscription(ctx context.Context, arg CreateCalendarSubscriptionParams) (sql.Result, error)
	CreateHatSwap(ctx context.Context, arg CreateHatSwapParams) (sql.Result, error)
	CreateLeaveRecord(ctx context.Context, arg CreateLeaveRecordParams) (sql.Result, error)
	CreateOAuthToken(ctx context.Context, arg CreateOAuthTokenParams) (OauthToken, error)
	CreateOutboxEntry(ctx context.Context, arg CreateOutboxEntryParams) (sql.Result, error)
	CreateRotaAssignment(ctx context.Context, arg CreateRotaAssignmentParams) (sql.Result, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// Atomically creates a user and makes them admin only if no admins exist
	CreateUserAsFirstAdmin(ctx context.Context, arg CreateUserAsFirstAdminParams) (User, error)
	CreateWFHRequest(ctx context.Context, arg CreateWFHRequestParams) (sql.Result, error)
	DeactivateAPIToken(ctx context.Context, id string) (sql.Result, error)
	DeactivateTeamMember(ctx context.Context, id string) error
	DeleteAPIToken(ctx context.Context, id string) (sql.Result, error)
	DeleteAssignmentsByDateRange(ctx context.Context, arg DeleteAssignmentsByDateRangeParams) error
	DeleteCalendarSubscription(ctx context.Context, token string) error
	DeleteExpiredLeaveRecords(ctx context.Context, endDate time.Time) error
	DeleteExpiredSessions(ctx context.Context) error
	DeleteHatSwap(ctx context.Context, id string) error
	DeleteLeaveRecord(ctx context.Context, id string) error
	DeleteMemberSubscriptions(ctx context.Context, memberID string) error
	DeleteOAuthToken(ctx context.Context, arg DeleteOAuthTokenParams) error
	DeleteRotaAssignment(ctx context.Context, id string) error
	DeleteSession(ctx context.Context, token string) error
	DeleteStaleSubscriptions(ctx context.Context, arg DeleteStaleSubscriptionsParams) (sql.Result, error)
	DeleteTeamMember(ctx context.Context, id string) error
	DeleteUserSessions(ctx context.Context, userID string) error
	DeleteWFHRequest(ctx context.Context, id string) error
	GetAPITokenByHash(ctx context.Context, tokenHash string) (ApiToken, error)
	GetAPITokenByID(ctx context.Context, id string) (ApiToken, error)
	GetAPITokensByUser(ctx context.Context, userID string) ([]ApiToken, error)
	GetActiveTeamMembers(ctx context.Context) ([]TeamMember, error)
	GetAllSubscriptions(ctx context.Context) ([]CalendarSubscription, error)
	GetAllWFHRequests(ctx context.Context) ([]GetAllWFHRequestsRow, error)
	GetAssignmentByID(ctx context.Context, id string) (GetAssignmentByIDRow, error)
	GetAssignmentsByDate(ctx context.Context, date time.Time) ([]GetAssignmentsByDateRow, error)
	GetAssignmentsByDateRange(ctx context.Context, arg GetAssignmentsByDateRangeParams) ([]GetAssignmentsByDateRangeRow, error)
	GetCoverAssignmentByDate(ctx context.Context, date time.Time) (GetCoverAssignmentByDateRow, error)
	GetFutureAssignments(ctx context.Context) ([]GetFutureAssignmentsRow, error)
	GetFutureAssignmentsForMember(ctx context.Context, memberID string) ([]GetFutureAssignmentsForMemberRow, error)
	GetHatSwapByID(ctx context.Context, id string) (HatSwap, error)
	GetLatestAssignmentDate(ctx context.Context) (interface{}, error)
	GetLeaveByDate(ctx context.Context, arg GetLeaveByDateParams) ([]LeaveRecord, error)
	GetLeaveByID(ctx context.Context, id string) (LeaveRecord, error)
	GetLeaveRecords(ctx context.Context, arg GetLeaveRecordsParams) ([]LeaveRecord, error)
	GetMemberByEmail(ctx context.Context, email string) (TeamMember, error)
	GetMemberByID(ctx context.Context, id string) (TeamMember, error)
	GetMemberByToken(ctx context.Context, token string) (TeamMember, error)
	// Returns the most recent cover assignment strictly BEFORE the supplied
	// reference date, so a future cover does not anchor the R2 rotation and
	// cause the same person to be picked for every new leave.
	GetMostRecentCoverAssignment(ctx context.Context, date time.Time) (GetMostRecentCoverAssignmentRow, error)
	// Returns the row for a member, or sql.ErrNoRows if no preference
	// has been set. The application treats the absence of a row as
	// "default" (email_enabled = 1).
	GetNotificationPreference(ctx context.Context, memberID string) (NotificationPreference, error)
	GetOAuthToken(ctx context.Context, arg GetOAuthTokenParams) (OauthToken, error)
	GetOpenSwapForAssignment(ctx context.Context, arg GetOpenSwapForAssignmentParams) (HatSwap, error)
	GetOutboxEntry(ctx context.Context, id string) (NotificationOutbox, error)
	GetPendingSwapsForMember(ctx context.Context, targetMemberID string) ([]HatSwap, error)
	GetPendingWFHRequestsForSettlement(ctx context.Context, date time.Time) ([]GetPendingWFHRequestsForSettlementRow, error)
	GetSessionByToken(ctx context.Context, token string) (GetSessionByTokenRow, error)
	GetSubscriptionByToken(ctx context.Context, token string) (CalendarSubscription, error)
	GetSubscriptionsByMemberID(ctx context.Context, memberID string) ([]CalendarSubscription, error)
	GetSwapsForMember(ctx context.Context, arg GetSwapsForMemberParams) ([]HatSwap, error)
	GetUpcomingAssignments(ctx context.Context, arg GetUpcomingAssignmentsParams) ([]GetUpcomingAssignmentsRow, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id string) (User, error)
	GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error)
	GetWFHRequestByID(ctx context.Context, id string) (GetWFHRequestByIDRow, error)
	GetWFHRequestByMemberAndDate(ctx context.Context, arg GetWFHRequestByMemberAndDateParams) (GetWFHRequestByMemberAndDateRow, error)
	GetWFHRequestsByDate(ctx context.Context, date time.Time) ([]GetWFHRequestsByDateRow, error)
	GetWFHRequestsByDateAndStatus(ctx context.Context, arg GetWFHRequestsByDateAndStatusParams) ([]GetWFHRequestsByDateAndStatusRow, error)
	GetWFHRequestsByMember(ctx context.Context, memberID string) ([]GetWFHRequestsByMemberRow, error)
	GetWFHRequestsByMemberAndPeriod(ctx context.Context, arg GetWFHRequestsByMemberAndPeriodParams) ([]GetWFHRequestsByMemberAndPeriodRow, error)
	// Returns 1 when the member has not disabled email, 0 when they
	// have. Returns 1 by default (no row) so callers don't have to
	// special-case "no preference set yet". The query is a single
	// parameter and a single scan, so the no-row case still produces
	// one row from the COALESCE branch.
	IsNotificationEmailEnabled(ctx context.Context, memberID string) (interface{}, error)
	ListActiveUsers(ctx context.Context) ([]User, error)
	ListAdminUsers(ctx context.Context) ([]User, error)
	MarkAssignmentSwapped(ctx context.Context, id string) error
	MarkOutboxDead(ctx context.Context, arg MarkOutboxDeadParams) (sql.Result, error)
	MarkOutboxFailed(ctx context.Context, arg MarkOutboxFailedParams) (sql.Result, error)
	MarkOutboxSent(ctx context.Context, id string) (sql.Result, error)
	// Upserts the email-enabled flag for a member. Pass 1 to enable,
	// 0 to disable. disabled_at is set/cleared by the application
	// before calling this query.
	SetNotificationEmailEnabled(ctx context.Context, arg SetNotificationEmailEnabledParams) error
	SetTeamMemberPermanentWFH(ctx context.Context, arg SetTeamMemberPermanentWFHParams) error
	SetTeamMemberRecurringWFHDays(ctx context.Context, arg SetTeamMemberRecurringWFHDaysParams) error
	TouchMeetingsSubscription(ctx context.Context, token string) error
	TouchRotaSubscription(ctx context.Context, token string) error
	UpdateAPITokenLastUsed(ctx context.Context, id string) (sql.Result, error)
	UpdateAssignmentMember(ctx context.Context, arg UpdateAssignmentMemberParams) error
	UpdateCoverMember(ctx context.Context, arg UpdateCoverMemberParams) error
	UpdateHatSwapStatus(ctx context.Context, arg UpdateHatSwapStatusParams) (sql.Result, error)
	UpdateLeaveCoverMember(ctx context.Context, arg UpdateLeaveCoverMemberParams) error
	UpdateLeaveRecord(ctx context.Context, arg UpdateLeaveRecordParams) error
	UpdateLeaveStatus(ctx context.Context, arg UpdateLeaveStatusParams) error
	UpdateOAuthToken(ctx context.Context, arg UpdateOAuthTokenParams) error
	UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) error
	UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) error
	UpdateWFHRequestStatus(ctx context.Context, arg UpdateWFHRequestStatusParams) (sql.Result, error)
	UpdateWFHRequestWithdrawn(ctx context.Context, arg UpdateWFHRequestWithdrawnParams) (sql.Result, error)
}

var _ Querier = (*Queries)(nil)
