// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: r1_rotation_state.sql

package sqlc

import (
	"context"
	"time"
)

const getR1RotationState = `-- name: GetR1RotationState :one
SELECT last_date, last_index
FROM r1_rotation_state
LIMIT 1
`

// Returns the R1 (original-HAT) rotation state, or sql.ErrNoRows
// if no R1 assignment has been written yet. The R1 rotation is
// kept in its own table (r1_rotation_state) so its write rules
// (only advance on successful assignment write) don't collide
// with the cover rotation's write rules (advance on every
// computation).
func (q *Queries) GetR1RotationState(ctx context.Context) (R1RotationState, error) {
	row := q.db.QueryRowContext(ctx, getR1RotationState)
	var i R1RotationState
	err := row.Scan(&i.LastDate, &i.LastIndex)
	return i, err
}

const upsertR1RotationState = `-- name: UpsertR1RotationState :exec
INSERT OR REPLACE INTO r1_rotation_state (last_date, last_index)
VALUES (?, ?)
`

type UpsertR1RotationStateParams struct {
	LastDate  time.Time `json:"last_date"`
	LastIndex int64     `json:"last_index"`
}

// Writes the R1 rotation state. The table holds at most one
// row, so this either inserts the first row or replaces the
// existing one. R1 is keyed by the (date, index) pair of the
// most recently written original assignment.
func (q *Queries) UpsertR1RotationState(ctx context.Context, arg UpsertR1RotationStateParams) error {
	_, err := q.db.ExecContext(ctx, upsertR1RotationState, arg.LastDate, arg.LastIndex)
	return err
}
