// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: rota_assignments.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const createRotaAssignment = `-- name: CreateRotaAssignment :execresult
INSERT INTO rota_assignments (id, date, member_id, is_cover, original_assignment_id)
VALUES (?, ?, ?, ?, ?)
`

type CreateRotaAssignmentParams struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
}

func (q *Queries) CreateRotaAssignment(ctx context.Context, arg CreateRotaAssignmentParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createRotaAssignment,
		arg.ID,
		arg.Date,
		arg.MemberID,
		arg.IsCover,
		arg.OriginalAssignmentID,
	)
}

const deleteAssignmentsByDateRange = `-- name: DeleteAssignmentsByDateRange :exec
DELETE FROM rota_assignments
WHERE date >= ? AND date <= ?
`

type DeleteAssignmentsByDateRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) DeleteAssignmentsByDateRange(ctx context.Context, arg DeleteAssignmentsByDateRangeParams) error {
	_, err := q.db.ExecContext(ctx, deleteAssignmentsByDateRange, arg.Date, arg.Date_2)
	return err
}

const deleteRotaAssignment = `-- name: DeleteRotaAssignment :exec
DELETE FROM rota_assignments
WHERE id = ?
`

func (q *Queries) DeleteRotaAssignment(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteRotaAssignment, id)
	return err
}

const getAssignmentByID = `-- name: GetAssignmentByID :one
SELECT id, date, member_id, is_cover, original_assignment_id, is_swapped
FROM rota_assignments
WHERE id = ?
`

type GetAssignmentByIDRow struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
}

func (q *Queries) GetAssignmentByID(ctx context.Context, id string) (GetAssignmentByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getAssignmentByID, id)
	var i GetAssignmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.MemberID,
		&i.IsCover,
		&i.OriginalAssignmentID,
		&i.IsSwapped,
	)
	return i, err
}

const getAssignmentsByDate = `-- name: GetAssignmentsByDate :many
SELECT ra.id, ra.date, ra.member_id, ra.is_cover, ra.original_assignment_id, ra.is_swapped, tm.name AS member_name, tm.email AS member_email
FROM rota_assignments ra
JOIN team_members tm ON ra.member_id = tm.id
WHERE ra.date = ?
`

type GetAssignmentsByDateRow struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
	MemberName           string         `json:"member_name"`
	MemberEmail          string         `json:"member_email"`
}

func (q *Queries) GetAssignmentsByDate(ctx context.Context, date time.Time) ([]GetAssignmentsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssignmentsByDateRow{}
	for rows.Next() {
		var i GetAssignmentsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.MemberID,
			&i.IsCover,
			&i.OriginalAssignmentID,
			&i.IsSwapped,
			&i.MemberName,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAssignmentsByDateRange = `-- name: GetAssignmentsByDateRange :many
SELECT ra.id, ra.date, ra.member_id, ra.is_cover, ra.original_assignment_id, ra.is_swapped, tm.name AS member_name, tm.email AS member_email
FROM rota_assignments ra
JOIN team_members tm ON ra.member_id = tm.id
WHERE ra.date >= ? AND ra.date <= ?
ORDER BY ra.date
`

type GetAssignmentsByDateRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

type GetAssignmentsByDateRangeRow struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
	MemberName           string         `json:"member_name"`
	MemberEmail          string         `json:"member_email"`
}

func (q *Queries) GetAssignmentsByDateRange(ctx context.Context, arg GetAssignmentsByDateRangeParams) ([]GetAssignmentsByDateRangeRow, error) {
	rows, err := q.db.QueryContext(ctx, getAssignmentsByDateRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAssignmentsByDateRangeRow{}
	for rows.Next() {
		var i GetAssignmentsByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.MemberID,
			&i.IsCover,
			&i.OriginalAssignmentID,
			&i.IsSwapped,
			&i.MemberName,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCoverAssignmentByDate = `-- name: GetCoverAssignmentByDate :one
SELECT id, date, member_id, is_cover, original_assignment_id, is_swapped
FROM rota_assignments
WHERE date = ? AND is_cover = 1
`

type GetCoverAssignmentByDateRow struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
}

func (q *Queries) GetCoverAssignmentByDate(ctx context.Context, date time.Time) (GetCoverAssignmentByDateRow, error) {
	row := q.db.QueryRowContext(ctx, getCoverAssignmentByDate, date)
	var i GetCoverAssignmentByDateRow
	err := row.Scan(
		&i.ID,
		&i.Date,
		&i.MemberID,
		&i.IsCover,
		&i.OriginalAssignmentID,
		&i.IsSwapped,
	)
	return i, err
}

const getCoveredOriginalIDsInRange = `-- name: GetCoveredOriginalIDsInRange :many
SELECT DISTINCT original_assignment_id AS original_id
FROM rota_assignments
WHERE is_cover = 1
  AND original_assignment_id IS NOT NULL
  AND date >= ?
  AND date <= ?
`

type GetCoveredOriginalIDsInRangeParams struct {
	Date   time.Time `json:"date"`
	Date_2 time.Time `json:"date_2"`
}

func (q *Queries) GetCoveredOriginalIDsInRange(ctx context.Context, arg GetCoveredOriginalIDsInRangeParams) ([]sql.NullString, error) {
	rows, err := q.db.QueryContext(ctx, getCoveredOriginalIDsInRange, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []sql.NullString{}
	for rows.Next() {
		var original_id sql.NullString
		if err := rows.Scan(&original_id); err != nil {
			return nil, err
		}
		items = append(items, original_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFutureAssignments = `-- name: GetFutureAssignments :many
SELECT ra.id, ra.date, ra.member_id, ra.is_cover, ra.original_assignment_id, ra.is_swapped,
       tm.name AS member_name, tm.email AS member_email
FROM rota_assignments ra
JOIN team_members tm ON ra.member_id = tm.id
WHERE ra.date >= date('now')
ORDER BY ra.date
`

type GetFutureAssignmentsRow struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
	MemberName           string         `json:"member_name"`
	MemberEmail          string         `json:"member_email"`
}

func (q *Queries) GetFutureAssignments(ctx context.Context) ([]GetFutureAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getFutureAssignments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFutureAssignmentsRow{}
	for rows.Next() {
		var i GetFutureAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.MemberID,
			&i.IsCover,
			&i.OriginalAssignmentID,
			&i.IsSwapped,
			&i.MemberName,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFutureAssignmentsForMember = `-- name: GetFutureAssignmentsForMember :many
SELECT ra.id, ra.date, ra.member_id, ra.is_cover, ra.original_assignment_id, ra.is_swapped,
       tm.name AS member_name, tm.email AS member_email
FROM rota_assignments ra
JOIN team_members tm ON ra.member_id = tm.id
WHERE ra.member_id = ? AND ra.date >= date('now')
ORDER BY ra.date
`

type GetFutureAssignmentsForMemberRow struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
	MemberName           string         `json:"member_name"`
	MemberEmail          string         `json:"member_email"`
}

func (q *Queries) GetFutureAssignmentsForMember(ctx context.Context, memberID string) ([]GetFutureAssignmentsForMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, getFutureAssignmentsForMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetFutureAssignmentsForMemberRow{}
	for rows.Next() {
		var i GetFutureAssignmentsForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.MemberID,
			&i.IsCover,
			&i.OriginalAssignmentID,
			&i.IsSwapped,
			&i.MemberName,
			&i.MemberEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestAssignmentDate = `-- name: GetLatestAssignmentDate :one
SELECT MAX(date) AS max_date
FROM rota_assignments
`

func (q *Queries) GetLatestAssignmentDate(ctx context.Context) (interface{}, error) {
	row := q.db.QueryRowContext(ctx, getLatestAssignmentDate)
	var max_date interface{}
	err := row.Scan(&max_date)
	return max_date, err
}

const getUpcomingAssignments = `-- name: GetUpcomingAssignments :many
SELECT id, date, member_id, is_cover, original_assignment_id, is_swapped
FROM rota_assignments
WHERE member_id = ? AND date >= date('now') AND date <= date('now', '+' || ? || ' days')
ORDER BY date
`

type GetUpcomingAssignmentsParams struct {
	MemberID string         `json:"member_id"`
	Column2  sql.NullString `json:"column_2"`
}

type GetUpcomingAssignmentsRow struct {
	ID                   string         `json:"id"`
	Date                 time.Time      `json:"date"`
	MemberID             string         `json:"member_id"`
	IsCover              sql.NullInt64  `json:"is_cover"`
	OriginalAssignmentID sql.NullString `json:"original_assignment_id"`
	IsSwapped            int64          `json:"is_swapped"`
}

func (q *Queries) GetUpcomingAssignments(ctx context.Context, arg GetUpcomingAssignmentsParams) ([]GetUpcomingAssignmentsRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingAssignments, arg.MemberID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingAssignmentsRow{}
	for rows.Next() {
		var i GetUpcomingAssignmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.Date,
			&i.MemberID,
			&i.IsCover,
			&i.OriginalAssignmentID,
			&i.IsSwapped,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAssignmentSwapped = `-- name: MarkAssignmentSwapped :exec
UPDATE rota_assignments
SET is_swapped = 1
WHERE id = ?
`

func (q *Queries) MarkAssignmentSwapped(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, markAssignmentSwapped, id)
	return err
}

const updateAssignmentMember = `-- name: UpdateAssignmentMember :exec
UPDATE rota_assignments
SET member_id = ?
WHERE id = ?
`

type UpdateAssignmentMemberParams struct {
	MemberID string `json:"member_id"`
	ID       string `json:"id"`
}

func (q *Queries) UpdateAssignmentMember(ctx context.Context, arg UpdateAssignmentMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateAssignmentMember, arg.MemberID, arg.ID)
	return err
}

const updateCoverMember = `-- name: UpdateCoverMember :exec
UPDATE rota_assignments
SET member_id = ?
WHERE date = ? AND is_cover = 1
`

type UpdateCoverMemberParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
}

func (q *Queries) UpdateCoverMember(ctx context.Context, arg UpdateCoverMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateCoverMember, arg.MemberID, arg.Date)
	return err
}
