// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: team_members.sql

package sqlc

import (
	"context"
	"database/sql"
)

const activateTeamMember = `-- name: ActivateTeamMember :exec
UPDATE team_members
SET is_active = 1
WHERE id = ?
`

func (q *Queries) ActivateTeamMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, activateTeamMember, id)
	return err
}

const addTeamMember = `-- name: AddTeamMember :execresult
INSERT INTO team_members (id, name, email)
VALUES (?, ?, ?)
`

type AddTeamMemberParams struct {
	ID    string `json:"id"`
	Name  string `json:"name"`
	Email string `json:"email"`
}

func (q *Queries) AddTeamMember(ctx context.Context, arg AddTeamMemberParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, addTeamMember, arg.ID, arg.Name, arg.Email)
}

const deactivateTeamMember = `-- name: DeactivateTeamMember :exec
UPDATE team_members
SET is_active = 0
WHERE id = ?
`

func (q *Queries) DeactivateTeamMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deactivateTeamMember, id)
	return err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
DELETE FROM team_members
WHERE id = ?
`

func (q *Queries) DeleteTeamMember(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteTeamMember, id)
	return err
}

const getActiveTeamMembers = `-- name: GetActiveTeamMembers :many
SELECT id, name, email, is_active, is_permanent_wfh, created_at
FROM team_members
WHERE is_active = 1
ORDER BY name
`

func (q *Queries) GetActiveTeamMembers(ctx context.Context) ([]TeamMember, error) {
	rows, err := q.db.QueryContext(ctx, getActiveTeamMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TeamMember{}
	for rows.Next() {
		var i TeamMember
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.IsActive,
			&i.IsPermanentWfh,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMemberByEmail = `-- name: GetMemberByEmail :one
SELECT id, name, email, is_active, is_permanent_wfh, created_at
FROM team_members
WHERE email = ?
`

func (q *Queries) GetMemberByEmail(ctx context.Context, email string) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getMemberByEmail, email)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsActive,
		&i.IsPermanentWfh,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberByID = `-- name: GetMemberByID :one
SELECT id, name, email, is_active, is_permanent_wfh, created_at
FROM team_members
WHERE id = ?
`

func (q *Queries) GetMemberByID(ctx context.Context, id string) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getMemberByID, id)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsActive,
		&i.IsPermanentWfh,
		&i.CreatedAt,
	)
	return i, err
}

const getMemberByToken = `-- name: GetMemberByToken :one
SELECT tm.id, tm.name, tm.email, tm.is_active, tm.is_permanent_wfh, tm.created_at
FROM calendar_subscriptions cs
JOIN team_members tm ON cs.member_id = tm.id
WHERE cs.token = ?
`

func (q *Queries) GetMemberByToken(ctx context.Context, token string) (TeamMember, error) {
	row := q.db.QueryRowContext(ctx, getMemberByToken, token)
	var i TeamMember
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.IsActive,
		&i.IsPermanentWfh,
		&i.CreatedAt,
	)
	return i, err
}

const setTeamMemberPermanentWFH = `-- name: SetTeamMemberPermanentWFH :exec
UPDATE team_members
SET is_permanent_wfh = ?
WHERE id = ?
`

type SetTeamMemberPermanentWFHParams struct {
	IsPermanentWfh int64  `json:"is_permanent_wfh"`
	ID             string `json:"id"`
}

func (q *Queries) SetTeamMemberPermanentWFH(ctx context.Context, arg SetTeamMemberPermanentWFHParams) error {
	_, err := q.db.ExecContext(ctx, setTeamMemberPermanentWFH, arg.IsPermanentWfh, arg.ID)
	return err
}

const updateTeamMember = `-- name: UpdateTeamMember :exec
UPDATE team_members
SET name = ?, email = ?
WHERE id = ?
`

type UpdateTeamMemberParams struct {
	Name  string `json:"name"`
	Email string `json:"email"`
	ID    string `json:"id"`
}

func (q *Queries) UpdateTeamMember(ctx context.Context, arg UpdateTeamMemberParams) error {
	_, err := q.db.ExecContext(ctx, updateTeamMember, arg.Name, arg.Email, arg.ID)
	return err
}
