// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"database/sql"
)

const countAdmins = `-- name: CountAdmins :one
SELECT COUNT(*) FROM users 
WHERE is_admin = 1 AND is_active = 1
`

func (q *Queries) CountAdmins(ctx context.Context) (int64, error) {
	row := q.db.QueryRowContext(ctx, countAdmins)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    id, email, name, provider, provider_id, is_admin, is_active
) VALUES (
    ?, ?, ?, ?, ?, ?, ?
)
RETURNING id, email, name, provider, provider_id, is_admin, is_active, created_at, updated_at
`

type CreateUserParams struct {
	ID         string        `json:"id"`
	Email      string        `json:"email"`
	Name       string        `json:"name"`
	Provider   string        `json:"provider"`
	ProviderID string        `json:"provider_id"`
	IsAdmin    sql.NullInt64 `json:"is_admin"`
	IsActive   sql.NullInt64 `json:"is_active"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Provider,
		arg.ProviderID,
		arg.IsAdmin,
		arg.IsActive,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.ProviderID,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createUserAsFirstAdmin = `-- name: CreateUserAsFirstAdmin :one
INSERT INTO users (
    id, email, name, provider, provider_id, is_admin, is_active
)
SELECT ?, ?, ?, ?, ?, 
    CASE WHEN (SELECT COUNT(*) FROM users WHERE is_admin = 1 AND is_active = 1) = 0 THEN 1 ELSE 0 END,
    1
RETURNING id, email, name, provider, provider_id, is_admin, is_active, created_at, updated_at
`

type CreateUserAsFirstAdminParams struct {
	ID         string `json:"id"`
	Email      string `json:"email"`
	Name       string `json:"name"`
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

// Atomically creates a user and makes them admin only if no admins exist
func (q *Queries) CreateUserAsFirstAdmin(ctx context.Context, arg CreateUserAsFirstAdminParams) (User, error) {
	row := q.db.QueryRowContext(ctx, createUserAsFirstAdmin,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Provider,
		arg.ProviderID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.ProviderID,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, email, name, provider, provider_id, is_admin, is_active, created_at, updated_at FROM users 
WHERE email = ? 
LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.ProviderID,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, email, name, provider, provider_id, is_admin, is_active, created_at, updated_at FROM users 
WHERE id = ? 
LIMIT 1
`

func (q *Queries) GetUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.ProviderID,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByProvider = `-- name: GetUserByProvider :one
SELECT id, email, name, provider, provider_id, is_admin, is_active, created_at, updated_at FROM users 
WHERE provider = ? AND provider_id = ? 
LIMIT 1
`

type GetUserByProviderParams struct {
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
}

func (q *Queries) GetUserByProvider(ctx context.Context, arg GetUserByProviderParams) (User, error) {
	row := q.db.QueryRowContext(ctx, getUserByProvider, arg.Provider, arg.ProviderID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Name,
		&i.Provider,
		&i.ProviderID,
		&i.IsAdmin,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
SELECT id, email, name, provider, provider_id, is_admin, is_active, created_at, updated_at FROM users 
WHERE is_active = 1 
ORDER BY name
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Provider,
			&i.ProviderID,
			&i.IsAdmin,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAdminUsers = `-- name: ListAdminUsers :many
SELECT id, email, name, provider, provider_id, is_admin, is_active, created_at, updated_at FROM users 
WHERE is_admin = 1 AND is_active = 1 
ORDER BY name
`

func (q *Queries) ListAdminUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.QueryContext(ctx, listAdminUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Name,
			&i.Provider,
			&i.ProviderID,
			&i.IsAdmin,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users 
SET 
    name = ?,
    is_admin = ?,
    is_active = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserParams struct {
	Name     string        `json:"name"`
	IsAdmin  sql.NullInt64 `json:"is_admin"`
	IsActive sql.NullInt64 `json:"is_active"`
	ID       string        `json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.ExecContext(ctx, updateUser,
		arg.Name,
		arg.IsAdmin,
		arg.IsActive,
		arg.ID,
	)
	return err
}

const updateUserProvider = `-- name: UpdateUserProvider :exec
UPDATE users 
SET 
    name = ?,
    provider = ?,
    provider_id = ?,
    updated_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateUserProviderParams struct {
	Name       string `json:"name"`
	Provider   string `json:"provider"`
	ProviderID string `json:"provider_id"`
	ID         string `json:"id"`
}

func (q *Queries) UpdateUserProvider(ctx context.Context, arg UpdateUserProviderParams) error {
	_, err := q.db.ExecContext(ctx, updateUserProvider,
		arg.Name,
		arg.Provider,
		arg.ProviderID,
		arg.ID,
	)
	return err
}
