// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wfh_co_presence.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const getLatestCoPresenceWithCohortA = `-- name: GetLatestCoPresenceWithCohortA :many
SELECT working_date
FROM wfh_co_presence
WHERE julianday(working_date) >= julianday(?)
  AND julianday(working_date) < julianday(?)
  AND member_id_a = ?
  AND member_id_b IN (?, ?, ?)
ORDER BY julianday(working_date) DESC
LIMIT 1
`

type GetLatestCoPresenceWithCohortAParams struct {
	Julianday   interface{} `json:"julianday"`
	Julianday_2 interface{} `json:"julianday_2"`
	MemberIDA   string      `json:"member_id_a"`
	MemberIDB   string      `json:"member_id_b"`
	MemberIDB_2 string      `json:"member_id_b_2"`
	MemberIDB_3 string      `json:"member_id_b_3"`
}

func (q *Queries) GetLatestCoPresenceWithCohortA(ctx context.Context, arg GetLatestCoPresenceWithCohortAParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, getLatestCoPresenceWithCohortA,
		arg.Julianday,
		arg.Julianday_2,
		arg.MemberIDA,
		arg.MemberIDB,
		arg.MemberIDB_2,
		arg.MemberIDB_3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var working_date time.Time
		if err := rows.Scan(&working_date); err != nil {
			return nil, err
		}
		items = append(items, working_date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLatestCoPresenceWithCohortB = `-- name: GetLatestCoPresenceWithCohortB :many
SELECT working_date
FROM wfh_co_presence
WHERE julianday(working_date) >= julianday(?)
  AND julianday(working_date) < julianday(?)
  AND member_id_b = ?
  AND member_id_a IN (?, ?, ?)
ORDER BY julianday(working_date) DESC
LIMIT 1
`

type GetLatestCoPresenceWithCohortBParams struct {
	Julianday   interface{} `json:"julianday"`
	Julianday_2 interface{} `json:"julianday_2"`
	MemberIDB   string      `json:"member_id_b"`
	MemberIDA   string      `json:"member_id_a"`
	MemberIDA_2 string      `json:"member_id_a_2"`
	MemberIDA_3 string      `json:"member_id_a_3"`
}

func (q *Queries) GetLatestCoPresenceWithCohortB(ctx context.Context, arg GetLatestCoPresenceWithCohortBParams) ([]time.Time, error) {
	rows, err := q.db.QueryContext(ctx, getLatestCoPresenceWithCohortB,
		arg.Julianday,
		arg.Julianday_2,
		arg.MemberIDB,
		arg.MemberIDA,
		arg.MemberIDA_2,
		arg.MemberIDA_3,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []time.Time{}
	for rows.Next() {
		var working_date time.Time
		if err := rows.Scan(&working_date); err != nil {
			return nil, err
		}
		items = append(items, working_date)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const pruneCoPresenceOlderThan = `-- name: PruneCoPresenceOlderThan :execresult
DELETE FROM wfh_co_presence WHERE julianday(working_date) < julianday(?)
`

func (q *Queries) PruneCoPresenceOlderThan(ctx context.Context, julianday interface{}) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneCoPresenceOlderThan, julianday)
}

const recordWFHCoPresencePair = `-- name: RecordWFHCoPresencePair :execresult
INSERT OR IGNORE INTO wfh_co_presence (co_presence_id, working_date, member_id_a, member_id_b)
VALUES (?, ?, ?, ?)
`

type RecordWFHCoPresencePairParams struct {
	CoPresenceID string    `json:"co_presence_id"`
	WorkingDate  time.Time `json:"working_date"`
	MemberIDA    string    `json:"member_id_a"`
	MemberIDB    string    `json:"member_id_b"`
}

func (q *Queries) RecordWFHCoPresencePair(ctx context.Context, arg RecordWFHCoPresencePairParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recordWFHCoPresencePair,
		arg.CoPresenceID,
		arg.WorkingDate,
		arg.MemberIDA,
		arg.MemberIDB,
	)
}
