// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wfh_co_presence.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const pruneCoPresenceOlderThan = `-- name: PruneCoPresenceOlderThan :execresult
DELETE FROM wfh_co_presence WHERE working_date < ?
`

func (q *Queries) PruneCoPresenceOlderThan(ctx context.Context, workingDate time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, pruneCoPresenceOlderThan, workingDate)
}

const recordWFHCoPresencePair = `-- name: RecordWFHCoPresencePair :execresult
INSERT OR IGNORE INTO wfh_co_presence (co_presence_id, working_date, member_id_a, member_id_b)
VALUES (?, ?, ?, ?)
`

type RecordWFHCoPresencePairParams struct {
	CoPresenceID string    `json:"co_presence_id"`
	WorkingDate  time.Time `json:"working_date"`
	MemberIDA    string    `json:"member_id_a"`
	MemberIDB    string    `json:"member_id_b"`
}

func (q *Queries) RecordWFHCoPresencePair(ctx context.Context, arg RecordWFHCoPresencePairParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, recordWFHCoPresencePair,
		arg.CoPresenceID,
		arg.WorkingDate,
		arg.MemberIDA,
		arg.MemberIDB,
	)
}
