// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wfh_requests.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countApprovedWFHByDate = `-- name: CountApprovedWFHByDate :one
SELECT COUNT(*) AS count
FROM wfh_requests
WHERE date = ? AND status = 'approved'
`

func (q *Queries) CountApprovedWFHByDate(ctx context.Context, date time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApprovedWFHByDate, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWFHRequestsBefore = `-- name: CountWFHRequestsBefore :one
SELECT COUNT(*) AS count
FROM wfh_requests
WHERE date < ?
`

// Count wfh_requests rows whose date is strictly before the cutoff.
// Used by the past-period purge dry-run to preview the affected row
// count without touching the table. The cutoff is the start of the
// previous quota period: rows on or after that date are kept.
func (q *Queries) CountWFHRequestsBefore(ctx context.Context, date time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWFHRequestsBefore, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovedRecurringWFHRequest = `-- name: CreateApprovedRecurringWFHRequest :execresult
INSERT INTO wfh_requests (id, member_id, date, status, is_recurring, settled_at)
VALUES (?, ?, ?, 'approved', 1, ?)
`

type CreateApprovedRecurringWFHRequestParams struct {
	ID        string       `json:"id"`
	MemberID  string       `json:"member_id"`
	Date      time.Time    `json:"date"`
	SettledAt sql.NullTime `json:"settled_at"`
}

func (q *Queries) CreateApprovedRecurringWFHRequest(ctx context.Context, arg CreateApprovedRecurringWFHRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createApprovedRecurringWFHRequest,
		arg.ID,
		arg.MemberID,
		arg.Date,
		arg.SettledAt,
	)
}

const createWFHRequest = `-- name: CreateWFHRequest :execresult
INSERT INTO wfh_requests (id, member_id, date, status)
VALUES (?, ?, ?, 'pending')
`

type CreateWFHRequestParams struct {
	ID       string    `json:"id"`
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
}

func (q *Queries) CreateWFHRequest(ctx context.Context, arg CreateWFHRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWFHRequest, arg.ID, arg.MemberID, arg.Date)
}

const deleteWFHRequest = `-- name: DeleteWFHRequest :exec
DELETE FROM wfh_requests
WHERE id = ?
`

func (q *Queries) DeleteWFHRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWFHRequest, id)
	return err
}

const getAllWFHRequests = `-- name: GetAllWFHRequests :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
ORDER BY date DESC, created_at DESC
`

type GetAllWFHRequestsRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetAllWFHRequests(ctx context.Context) ([]GetAllWFHRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWFHRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllWFHRequestsRow{}
	for rows.Next() {
		var i GetAllWFHRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWFHRequestsForSettlement = `-- name: GetPendingWFHRequestsForSettlement :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
WHERE status = 'pending'
  AND is_recurring = 0
  AND date <= ?
ORDER BY date ASC, created_at ASC
`

type GetPendingWFHRequestsForSettlementRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetPendingWFHRequestsForSettlement(ctx context.Context, date time.Time) ([]GetPendingWFHRequestsForSettlementRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingWFHRequestsForSettlement, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingWFHRequestsForSettlementRow{}
	for rows.Next() {
		var i GetPendingWFHRequestsForSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestByID = `-- name: GetWFHRequestByID :one
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
WHERE id = ?
`

type GetWFHRequestByIDRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetWFHRequestByID(ctx context.Context, id string) (GetWFHRequestByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWFHRequestByID, id)
	var i GetWFHRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.WithdrawnBy,
		&i.WithdrawnAt,
		&i.IsRecurring,
		&i.IsAdminMarked,
		&i.MarkedBy,
		&i.MarkedAt,
	)
	return i, err
}

const getWFHRequestByMemberAndDate = `-- name: GetWFHRequestByMemberAndDate :one
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
WHERE member_id = ? AND date = ?
`

type GetWFHRequestByMemberAndDateParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
}

type GetWFHRequestByMemberAndDateRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetWFHRequestByMemberAndDate(ctx context.Context, arg GetWFHRequestByMemberAndDateParams) (GetWFHRequestByMemberAndDateRow, error) {
	row := q.db.QueryRowContext(ctx, getWFHRequestByMemberAndDate, arg.MemberID, arg.Date)
	var i GetWFHRequestByMemberAndDateRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.WithdrawnBy,
		&i.WithdrawnAt,
		&i.IsRecurring,
		&i.IsAdminMarked,
		&i.MarkedBy,
		&i.MarkedAt,
	)
	return i, err
}

const getWFHRequestsByDate = `-- name: GetWFHRequestsByDate :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
WHERE date = ?
ORDER BY created_at ASC
`

type GetWFHRequestsByDateRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetWFHRequestsByDate(ctx context.Context, date time.Time) ([]GetWFHRequestsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByDateRow{}
	for rows.Next() {
		var i GetWFHRequestsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestsByDateAndStatus = `-- name: GetWFHRequestsByDateAndStatus :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
WHERE date = ? AND status = ?
ORDER BY created_at ASC
`

type GetWFHRequestsByDateAndStatusParams struct {
	Date   time.Time `json:"date"`
	Status string    `json:"status"`
}

type GetWFHRequestsByDateAndStatusRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetWFHRequestsByDateAndStatus(ctx context.Context, arg GetWFHRequestsByDateAndStatusParams) ([]GetWFHRequestsByDateAndStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByDateAndStatus, arg.Date, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByDateAndStatusRow{}
	for rows.Next() {
		var i GetWFHRequestsByDateAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestsByMember = `-- name: GetWFHRequestsByMember :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
WHERE member_id = ?
ORDER BY date DESC
`

type GetWFHRequestsByMemberRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetWFHRequestsByMember(ctx context.Context, memberID string) ([]GetWFHRequestsByMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByMemberRow{}
	for rows.Next() {
		var i GetWFHRequestsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestsByMemberAndPeriod = `-- name: GetWFHRequestsByMemberAndPeriod :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at
FROM wfh_requests
WHERE member_id = ?
  AND date >= ?
  AND date <= ?
  AND status IN ('pending', 'approved')
ORDER BY date ASC
`

type GetWFHRequestsByMemberAndPeriodParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
	Date_2   time.Time `json:"date_2"`
}

type GetWFHRequestsByMemberAndPeriodRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
}

func (q *Queries) GetWFHRequestsByMemberAndPeriod(ctx context.Context, arg GetWFHRequestsByMemberAndPeriodParams) ([]GetWFHRequestsByMemberAndPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByMemberAndPeriod, arg.MemberID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByMemberAndPeriodRow{}
	for rows.Next() {
		var i GetWFHRequestsByMemberAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAdminMarkedWFH = `-- name: IsAdminMarkedWFH :one
SELECT is_admin_marked
FROM wfh_requests
WHERE member_id = ? AND date = ?
`

type IsAdminMarkedWFHParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
}

// Returns 1 if an admin-marked row exists for (member_id, date),
// 0 otherwise. Cheap point-lookup behind the
// idx_wfh_requests_admin_marked index.
func (q *Queries) IsAdminMarkedWFH(ctx context.Context, arg IsAdminMarkedWFHParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isAdminMarkedWFH, arg.MemberID, arg.Date)
	var is_admin_marked int64
	err := row.Scan(&is_admin_marked)
	return is_admin_marked, err
}

const markAdminWFH = `-- name: MarkAdminWFH :execresult
INSERT INTO wfh_requests (id, member_id, date, status, is_admin_marked, marked_by, marked_at)
VALUES (?, ?, ?, 'approved', 1, ?, ?)
`

type MarkAdminWFHParams struct {
	ID       string         `json:"id"`
	MemberID string         `json:"member_id"`
	Date     time.Time      `json:"date"`
	MarkedBy sql.NullString `json:"marked_by"`
	MarkedAt sql.NullTime   `json:"marked_at"`
}

// Insert an admin-marked WFH row in one shot. is_admin_marked=1 and
// status='approved' so the row participates in every existing
// query (quota, floor, ICS, dashboard presence) without the
// rendering layer needing a special case for admin marks. The
// UNIQUE(member_id, date) constraint guarantees idempotency: a
// second mark for the same (member, date) returns SQLITE_CONSTRAINT
// to the caller, which the service layer translates into
// "already marked".
func (q *Queries) MarkAdminWFH(ctx context.Context, arg MarkAdminWFHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markAdminWFH,
		arg.ID,
		arg.MemberID,
		arg.Date,
		arg.MarkedBy,
		arg.MarkedAt,
	)
}

const purgeWFHRequestsBefore = `-- name: PurgeWFHRequestsBefore :execresult
DELETE FROM wfh_requests WHERE date < ?
`

// NOTE: comments must follow the SQL, not precede it. sqlc v1.28.0 has a
// parser bug that strips the trailing `?` from multi-line DELETE statements
// ending in `< ?` when there are `--` comment lines between `-- name:` and
// the statement. Keep this statement on a single line with comments below.
func (q *Queries) PurgeWFHRequestsBefore(ctx context.Context, date time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, purgeWFHRequestsBefore, date)
}

const resurrectWFHRequest = `-- name: ResurrectWFHRequest :execresult
UPDATE wfh_requests
SET status = 'pending',
    settled_at = NULL,
    withdrawn_by = NULL,
    withdrawn_at = NULL,
    is_recurring = 0
WHERE id = ?
  AND (
    status = 'cancelled'
    OR (status = 'withdrawn' AND withdrawn_by IS NULL)
  )
`

// Flip a previously cancelled or self-withdrawn row back to pending and
// clear the audit fields, so the user can change their mind and re-request
// WFH for the same date. Only self-withdrawals are resurrectable: admin
// withdrawals (withdrawn_by IS NOT NULL) are preserved as final decisions.
// is_recurring is cleared on resurrect so the row is treated as ad-hoc:
// settlement filters is_recurring=0 (so recurring rows are skipped), and
// preserving the flag would leave the resurrected row stuck in pending
// with neither settlement nor the materializer able to advance it.
func (q *Queries) ResurrectWFHRequest(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, resurrectWFHRequest, id)
}

const updateWFHRequestStatus = `-- name: UpdateWFHRequestStatus :execresult
UPDATE wfh_requests
SET status = ?, settled_at = ?
WHERE id = ?
`

type UpdateWFHRequestStatusParams struct {
	Status    string       `json:"status"`
	SettledAt sql.NullTime `json:"settled_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateWFHRequestStatus(ctx context.Context, arg UpdateWFHRequestStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWFHRequestStatus, arg.Status, arg.SettledAt, arg.ID)
}

const updateWFHRequestWithdrawn = `-- name: UpdateWFHRequestWithdrawn :execresult
UPDATE wfh_requests
SET status = 'withdrawn', withdrawn_by = ?, withdrawn_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWFHRequestWithdrawnParams struct {
	WithdrawnBy sql.NullString `json:"withdrawn_by"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateWFHRequestWithdrawn(ctx context.Context, arg UpdateWFHRequestWithdrawnParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWFHRequestWithdrawn, arg.WithdrawnBy, arg.ID)
}
