// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wfh_requests.sql

package sqlc

import (
	"context"
	"database/sql"
	"time"
)

const countApprovedWFHByDate = `-- name: CountApprovedWFHByDate :one
SELECT COUNT(*) AS count
FROM wfh_requests
WHERE date = ? AND status = 'approved'
`

func (q *Queries) CountApprovedWFHByDate(ctx context.Context, date time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countApprovedWFHByDate, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countWFHRequestsBefore = `-- name: CountWFHRequestsBefore :one
SELECT COUNT(*) AS count
FROM wfh_requests
WHERE date < ?
`

func (q *Queries) CountWFHRequestsBefore(ctx context.Context, date time.Time) (int64, error) {
	row := q.db.QueryRowContext(ctx, countWFHRequestsBefore, date)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createApprovedAssignedWFHRequest = `-- name: CreateApprovedAssignedWFHRequest :execresult
INSERT INTO wfh_requests (id, member_id, date, status, is_recurring, settled_at, origin)
VALUES (?, ?, ?, 'approved', 0, ?, 'assigned')
`

type CreateApprovedAssignedWFHRequestParams struct {
	ID        string       `json:"id"`
	MemberID  string       `json:"member_id"`
	Date      time.Time    `json:"date"`
	SettledAt sql.NullTime `json:"settled_at"`
}

func (q *Queries) CreateApprovedAssignedWFHRequest(ctx context.Context, arg CreateApprovedAssignedWFHRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createApprovedAssignedWFHRequest,
		arg.ID,
		arg.MemberID,
		arg.Date,
		arg.SettledAt,
	)
}

const createApprovedRecurringWFHRequest = `-- name: CreateApprovedRecurringWFHRequest :execresult
INSERT INTO wfh_requests (id, member_id, date, status, is_recurring, settled_at, origin)
VALUES (?, ?, ?, 'approved', 1, ?, 'recurring')
`

type CreateApprovedRecurringWFHRequestParams struct {
	ID        string       `json:"id"`
	MemberID  string       `json:"member_id"`
	Date      time.Time    `json:"date"`
	SettledAt sql.NullTime `json:"settled_at"`
}

func (q *Queries) CreateApprovedRecurringWFHRequest(ctx context.Context, arg CreateApprovedRecurringWFHRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createApprovedRecurringWFHRequest,
		arg.ID,
		arg.MemberID,
		arg.Date,
		arg.SettledAt,
	)
}

const createWFHRequest = `-- name: CreateWFHRequest :execresult
INSERT INTO wfh_requests (id, member_id, date, status)
VALUES (?, ?, ?, 'pending')
`

type CreateWFHRequestParams struct {
	ID       string    `json:"id"`
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
}

// Mark a request as denied and record the human-readable reason in
// wfh_requests.denial_reason. The reason rides the same row to
// the dashboard, the WFH list page, the admin manage page, and
// the email notification so the user is never left guessing why their
// request was rejected.
func (q *Queries) CreateWFHRequest(ctx context.Context, arg CreateWFHRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createWFHRequest, arg.ID, arg.MemberID, arg.Date)
}

const deleteWFHRequest = `-- name: DeleteWFHRequest :exec
DELETE FROM wfh_requests
WHERE id = ?
`

func (q *Queries) DeleteWFHRequest(ctx context.Context, id string) error {
	_, err := q.db.ExecContext(ctx, deleteWFHRequest, id)
	return err
}

const denyWFHRequest = `-- name: DenyWFHRequest :execresult
UPDATE wfh_requests SET status = 'denied', settled_at = ?, denial_reason = ? WHERE id = ?
`

type DenyWFHRequestParams struct {
	SettledAt    sql.NullTime   `json:"settled_at"`
	DenialReason sql.NullString `json:"denial_reason"`
	ID           string         `json:"id"`
}

func (q *Queries) DenyWFHRequest(ctx context.Context, arg DenyWFHRequestParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, denyWFHRequest, arg.SettledAt, arg.DenialReason, arg.ID)
}

const getAllWFHRequests = `-- name: GetAllWFHRequests :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
ORDER BY date DESC, created_at DESC
`

type GetAllWFHRequestsRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetAllWFHRequests(ctx context.Context) ([]GetAllWFHRequestsRow, error) {
	rows, err := q.db.QueryContext(ctx, getAllWFHRequests)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetAllWFHRequestsRow{}
	for rows.Next() {
		var i GetAllWFHRequestsRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingWFHRequestsForSettlement = `-- name: GetPendingWFHRequestsForSettlement :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE status = 'pending'
  AND is_recurring = 0
  AND date <= ?
ORDER BY date ASC, created_at ASC
`

type GetPendingWFHRequestsForSettlementRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetPendingWFHRequestsForSettlement(ctx context.Context, date time.Time) ([]GetPendingWFHRequestsForSettlementRow, error) {
	rows, err := q.db.QueryContext(ctx, getPendingWFHRequestsForSettlement, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPendingWFHRequestsForSettlementRow{}
	for rows.Next() {
		var i GetPendingWFHRequestsForSettlementRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUpcomingWFHForMember = `-- name: GetUpcomingWFHForMember :many
SELECT id, member_id, date, status, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE member_id = ?
  AND date >= date('now')
  AND date <= date('now', '+' || ? || ' days')
  AND status = 'approved'
ORDER BY date
`

type GetUpcomingWFHForMemberParams struct {
	MemberID string         `json:"member_id"`
	Column2  sql.NullString `json:"column_2"`
}

type GetUpcomingWFHForMemberRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetUpcomingWFHForMember(ctx context.Context, arg GetUpcomingWFHForMemberParams) ([]GetUpcomingWFHForMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, getUpcomingWFHForMember, arg.MemberID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetUpcomingWFHForMemberRow{}
	for rows.Next() {
		var i GetUpcomingWFHForMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestByID = `-- name: GetWFHRequestByID :one
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE id = ?
`

type GetWFHRequestByIDRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetWFHRequestByID(ctx context.Context, id string) (GetWFHRequestByIDRow, error) {
	row := q.db.QueryRowContext(ctx, getWFHRequestByID, id)
	var i GetWFHRequestByIDRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.WithdrawnBy,
		&i.WithdrawnAt,
		&i.IsRecurring,
		&i.IsAdminMarked,
		&i.MarkedBy,
		&i.MarkedAt,
		&i.DenialReason,
		&i.Origin,
	)
	return i, err
}

const getWFHRequestByMemberAndDate = `-- name: GetWFHRequestByMemberAndDate :one
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE member_id = ? AND date = ?
`

type GetWFHRequestByMemberAndDateParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
}

type GetWFHRequestByMemberAndDateRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetWFHRequestByMemberAndDate(ctx context.Context, arg GetWFHRequestByMemberAndDateParams) (GetWFHRequestByMemberAndDateRow, error) {
	row := q.db.QueryRowContext(ctx, getWFHRequestByMemberAndDate, arg.MemberID, arg.Date)
	var i GetWFHRequestByMemberAndDateRow
	err := row.Scan(
		&i.ID,
		&i.MemberID,
		&i.Date,
		&i.Status,
		&i.CreatedAt,
		&i.SettledAt,
		&i.WithdrawnBy,
		&i.WithdrawnAt,
		&i.IsRecurring,
		&i.IsAdminMarked,
		&i.MarkedBy,
		&i.MarkedAt,
		&i.DenialReason,
		&i.Origin,
	)
	return i, err
}

const getWFHRequestsByDate = `-- name: GetWFHRequestsByDate :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE date = ?
ORDER BY created_at ASC
`

type GetWFHRequestsByDateRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetWFHRequestsByDate(ctx context.Context, date time.Time) ([]GetWFHRequestsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByDate, date)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByDateRow{}
	for rows.Next() {
		var i GetWFHRequestsByDateRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestsByDateAndStatus = `-- name: GetWFHRequestsByDateAndStatus :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE date = ? AND status = ?
ORDER BY created_at ASC
`

type GetWFHRequestsByDateAndStatusParams struct {
	Date   time.Time `json:"date"`
	Status string    `json:"status"`
}

type GetWFHRequestsByDateAndStatusRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetWFHRequestsByDateAndStatus(ctx context.Context, arg GetWFHRequestsByDateAndStatusParams) ([]GetWFHRequestsByDateAndStatusRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByDateAndStatus, arg.Date, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByDateAndStatusRow{}
	for rows.Next() {
		var i GetWFHRequestsByDateAndStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestsByMember = `-- name: GetWFHRequestsByMember :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE member_id = ?
ORDER BY date DESC
`

type GetWFHRequestsByMemberRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetWFHRequestsByMember(ctx context.Context, memberID string) ([]GetWFHRequestsByMemberRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByMember, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByMemberRow{}
	for rows.Next() {
		var i GetWFHRequestsByMemberRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestsByMemberAndPeriod = `-- name: GetWFHRequestsByMemberAndPeriod :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE member_id = ?
  AND date >= ?
  AND date <= ?
  AND status IN ('pending', 'approved')
ORDER BY date ASC
`

type GetWFHRequestsByMemberAndPeriodParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
	Date_2   time.Time `json:"date_2"`
}

type GetWFHRequestsByMemberAndPeriodRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetWFHRequestsByMemberAndPeriod(ctx context.Context, arg GetWFHRequestsByMemberAndPeriodParams) ([]GetWFHRequestsByMemberAndPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsByMemberAndPeriod, arg.MemberID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsByMemberAndPeriodRow{}
	for rows.Next() {
		var i GetWFHRequestsByMemberAndPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getWFHRequestsVoluntaryInPeriod = `-- name: GetWFHRequestsVoluntaryInPeriod :many
SELECT id, member_id, date, status, created_at, settled_at, withdrawn_by, withdrawn_at, is_recurring, is_admin_marked, marked_by, marked_at, denial_reason, origin
FROM wfh_requests
WHERE member_id = ?
  AND date >= ?
  AND date <= ?
  AND status IN ('pending', 'approved')
  AND origin != 'assigned'
ORDER BY date ASC
`

type GetWFHRequestsVoluntaryInPeriodParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
	Date_2   time.Time `json:"date_2"`
}

type GetWFHRequestsVoluntaryInPeriodRow struct {
	ID            string         `json:"id"`
	MemberID      string         `json:"member_id"`
	Date          time.Time      `json:"date"`
	Status        string         `json:"status"`
	CreatedAt     sql.NullTime   `json:"created_at"`
	SettledAt     sql.NullTime   `json:"settled_at"`
	WithdrawnBy   sql.NullString `json:"withdrawn_by"`
	WithdrawnAt   sql.NullTime   `json:"withdrawn_at"`
	IsRecurring   int64          `json:"is_recurring"`
	IsAdminMarked int64          `json:"is_admin_marked"`
	MarkedBy      sql.NullString `json:"marked_by"`
	MarkedAt      sql.NullTime   `json:"marked_at"`
	DenialReason  sql.NullString `json:"denial_reason"`
	Origin        string         `json:"origin"`
}

func (q *Queries) GetWFHRequestsVoluntaryInPeriod(ctx context.Context, arg GetWFHRequestsVoluntaryInPeriodParams) ([]GetWFHRequestsVoluntaryInPeriodRow, error) {
	rows, err := q.db.QueryContext(ctx, getWFHRequestsVoluntaryInPeriod, arg.MemberID, arg.Date, arg.Date_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetWFHRequestsVoluntaryInPeriodRow{}
	for rows.Next() {
		var i GetWFHRequestsVoluntaryInPeriodRow
		if err := rows.Scan(
			&i.ID,
			&i.MemberID,
			&i.Date,
			&i.Status,
			&i.CreatedAt,
			&i.SettledAt,
			&i.WithdrawnBy,
			&i.WithdrawnAt,
			&i.IsRecurring,
			&i.IsAdminMarked,
			&i.MarkedBy,
			&i.MarkedAt,
			&i.DenialReason,
			&i.Origin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const isAdminMarkedWFH = `-- name: IsAdminMarkedWFH :one
SELECT is_admin_marked
FROM wfh_requests
WHERE member_id = ? AND date = ?
`

type IsAdminMarkedWFHParams struct {
	MemberID string    `json:"member_id"`
	Date     time.Time `json:"date"`
}

func (q *Queries) IsAdminMarkedWFH(ctx context.Context, arg IsAdminMarkedWFHParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, isAdminMarkedWFH, arg.MemberID, arg.Date)
	var is_admin_marked int64
	err := row.Scan(&is_admin_marked)
	return is_admin_marked, err
}

const markAdminWFH = `-- name: MarkAdminWFH :execresult
INSERT INTO wfh_requests (id, member_id, date, status, is_admin_marked, marked_by, marked_at)
VALUES (?, ?, ?, 'approved', 1, ?, ?)
`

type MarkAdminWFHParams struct {
	ID       string         `json:"id"`
	MemberID string         `json:"member_id"`
	Date     time.Time      `json:"date"`
	MarkedBy sql.NullString `json:"marked_by"`
	MarkedAt sql.NullTime   `json:"marked_at"`
}

func (q *Queries) MarkAdminWFH(ctx context.Context, arg MarkAdminWFHParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, markAdminWFH,
		arg.ID,
		arg.MemberID,
		arg.Date,
		arg.MarkedBy,
		arg.MarkedAt,
	)
}

const purgeWFHRequestsBefore = `-- name: PurgeWFHRequestsBefore :execresult
DELETE FROM wfh_requests WHERE date < ?
`

func (q *Queries) PurgeWFHRequestsBefore(ctx context.Context, date time.Time) (sql.Result, error) {
	return q.db.ExecContext(ctx, purgeWFHRequestsBefore, date)
}

const resurrectWFHRequest = `-- name: ResurrectWFHRequest :execresult
UPDATE wfh_requests
SET status = 'pending',
    settled_at = NULL,
    withdrawn_by = NULL,
    withdrawn_at = NULL,
    is_recurring = 0
WHERE id = ?
  AND (
    status = 'cancelled'
    OR (status = 'withdrawn' AND withdrawn_by IS NULL)
  )
`

func (q *Queries) ResurrectWFHRequest(ctx context.Context, id string) (sql.Result, error) {
	return q.db.ExecContext(ctx, resurrectWFHRequest, id)
}

const updateWFHRequestStatus = `-- name: UpdateWFHRequestStatus :execresult
UPDATE wfh_requests
SET status = ?, settled_at = ?
WHERE id = ?
`

type UpdateWFHRequestStatusParams struct {
	Status    string       `json:"status"`
	SettledAt sql.NullTime `json:"settled_at"`
	ID        string       `json:"id"`
}

func (q *Queries) UpdateWFHRequestStatus(ctx context.Context, arg UpdateWFHRequestStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWFHRequestStatus, arg.Status, arg.SettledAt, arg.ID)
}

const updateWFHRequestWithdrawn = `-- name: UpdateWFHRequestWithdrawn :execresult
UPDATE wfh_requests
SET status = 'withdrawn', withdrawn_by = ?, withdrawn_at = CURRENT_TIMESTAMP
WHERE id = ?
`

type UpdateWFHRequestWithdrawnParams struct {
	WithdrawnBy sql.NullString `json:"withdrawn_by"`
	ID          string         `json:"id"`
}

func (q *Queries) UpdateWFHRequestWithdrawn(ctx context.Context, arg UpdateWFHRequestWithdrawnParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateWFHRequestWithdrawn, arg.WithdrawnBy, arg.ID)
}
