// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.28.0
// source: wfh_assignment_swaps.sql

package sqlc

import (
	"context"
	"database/sql"
)

const cancelExpiredSwaps = `-- name: CancelExpiredSwaps :execresult
UPDATE wfh_assignment_swaps
SET status = 'cancelled',
    updated_at = CURRENT_TIMESTAMP,
    resolved_at = CURRENT_TIMESTAMP
WHERE status = 'pending'
  AND julianday(swap_date) < julianday(?)
`

// Auto-cancel pass run by SettlePendingRequests (step 15
// of plans/assigned-wfh-plan.md): flips every pending swap
// whose swap_date is strictly before today to status=
// 'cancelled'. The idx_wfh_assignment_swaps_date index
// covers this; the cutoff is computed in Go as today.
//
// Uses julianday() on both sides so the comparison is numeric
// rather than lexicographic. Without it, the ncruces driver
// encodes time.Time as RFC3339 ("YYYY-MM-DDTHH:MM:SSZ") while
// the column is stored as "YYYY-MM-DD" (DATE affinity, 10 chars);
// lexicographic compare fails for the boundary date, so a swap
// dated today gets auto-cancelled on every tick. See v0.31.5.
func (q *Queries) CancelExpiredSwaps(ctx context.Context, julianday interface{}) (sql.Result, error) {
	return q.db.ExecContext(ctx, cancelExpiredSwaps, julianday)
}

const createSwap = `-- name: CreateSwap :execresult
INSERT INTO wfh_assignment_swaps
    (id, requester_wfh_request_id, target_member_id, swap_date, status)
VALUES (?, ?, ?, julianday(?), 'pending')
`

type CreateSwapParams struct {
	ID                    string      `json:"id"`
	RequesterWfhRequestID string      `json:"requester_wfh_request_id"`
	TargetMemberID        string      `json:"target_member_id"`
	Julianday             interface{} `json:"julianday"`
}

// Insert a new pending swap request. Caller is responsible
// for the 409-conflict check (any pending swap for the same
// requester_wfh_request_id); the application enforces it
// before calling this query.
func (q *Queries) CreateSwap(ctx context.Context, arg CreateSwapParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, createSwap,
		arg.ID,
		arg.RequesterWfhRequestID,
		arg.TargetMemberID,
		arg.Julianday,
	)
}

const getPendingSwapForRequesterRow = `-- name: GetPendingSwapForRequesterRow :one
SELECT id, requester_wfh_request_id, target_member_id, swap_date, status,
       created_at, updated_at, resolved_at
FROM wfh_assignment_swaps
WHERE requester_wfh_request_id = ?
  AND status = 'pending'
`

// 409-conflict guard: returns the pending swap for a given
// assigned wfh_request row, if any. nil when no pending
// swap exists. Used in handleWFHSwapCreate before the
// INSERT to enforce "one pending swap per assigned row".
func (q *Queries) GetPendingSwapForRequesterRow(ctx context.Context, requesterWfhRequestID string) (WfhAssignmentSwap, error) {
	row := q.db.QueryRowContext(ctx, getPendingSwapForRequesterRow, requesterWfhRequestID)
	var i WfhAssignmentSwap
	err := row.Scan(
		&i.ID,
		&i.RequesterWfhRequestID,
		&i.TargetMemberID,
		&i.SwapDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const getPendingSwapsForRequester = `-- name: GetPendingSwapsForRequester :many
SELECT id, requester_wfh_request_id, target_member_id, swap_date, status,
       created_at, updated_at, resolved_at
FROM wfh_assignment_swaps
WHERE requester_wfh_request_id IN
    (SELECT id FROM wfh_requests WHERE member_id = ?)
  AND status = 'pending'
ORDER BY created_at DESC
`

// Outbound read for the requester. Returns all swaps the
// current member has opened that are still pending. Used
// by the swap form to show "your swap is awaiting N's
// decision" and by the cancel button.
func (q *Queries) GetPendingSwapsForRequester(ctx context.Context, memberID string) ([]WfhAssignmentSwap, error) {
	rows, err := q.db.QueryContext(ctx, getPendingSwapsForRequester, memberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfhAssignmentSwap{}
	for rows.Next() {
		var i WfhAssignmentSwap
		if err := rows.Scan(
			&i.ID,
			&i.RequesterWfhRequestID,
			&i.TargetMemberID,
			&i.SwapDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPendingSwapsForTarget = `-- name: GetPendingSwapsForTarget :many
SELECT id, requester_wfh_request_id, target_member_id, swap_date, status,
       created_at, updated_at, resolved_at
FROM wfh_assignment_swaps
WHERE target_member_id = ?
  AND status = 'pending'
ORDER BY created_at DESC
`

// Inbox read for the target member. Returns all swaps where
// the target is the current user and status='pending'. The
// idx_wfh_assignment_swaps_target index covers this.
func (q *Queries) GetPendingSwapsForTarget(ctx context.Context, targetMemberID string) ([]WfhAssignmentSwap, error) {
	rows, err := q.db.QueryContext(ctx, getPendingSwapsForTarget, targetMemberID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []WfhAssignmentSwap{}
	for rows.Next() {
		var i WfhAssignmentSwap
		if err := rows.Scan(
			&i.ID,
			&i.RequesterWfhRequestID,
			&i.TargetMemberID,
			&i.SwapDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSwapByID = `-- name: GetSwapByID :one
SELECT id, requester_wfh_request_id, target_member_id, swap_date, status,
       created_at, updated_at, resolved_at
FROM wfh_assignment_swaps
WHERE id = ?
`

func (q *Queries) GetSwapByID(ctx context.Context, id string) (WfhAssignmentSwap, error) {
	row := q.db.QueryRowContext(ctx, getSwapByID, id)
	var i WfhAssignmentSwap
	err := row.Scan(
		&i.ID,
		&i.RequesterWfhRequestID,
		&i.TargetMemberID,
		&i.SwapDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ResolvedAt,
	)
	return i, err
}

const updateSwapStatus = `-- name: UpdateSwapStatus :execresult
UPDATE wfh_assignment_swaps
SET status = ?, updated_at = CURRENT_TIMESTAMP, resolved_at = ?
WHERE id = ?
`

type UpdateSwapStatusParams struct {
	Status     string       `json:"status"`
	ResolvedAt sql.NullTime `json:"resolved_at"`
	ID         string       `json:"id"`
}

// State transition for accept / reject / cancel. Caller
// passes the new status string and a resolved_at
// timestamp. status='cancelled' is used by both the requester
// (voluntary) and the scheduler (auto-cancel because the
// date passed).
func (q *Queries) UpdateSwapStatus(ctx context.Context, arg UpdateSwapStatusParams) (sql.Result, error) {
	return q.db.ExecContext(ctx, updateSwapStatus, arg.Status, arg.ResolvedAt, arg.ID)
}
